.storybook/preview-head.html
package.json
src/components/Button/Button.js
src/components/Button/Button.stories.mdx
src/components/Button/Button.test.js

* Add `is-disabled` class for any element type that is not "button".
* Fix Storybook markdown for disabled components.
* Fix typo in package.json peer-dependencies.
* Fix illegible plaintext in preview code blocks.
* Run storybook, visit Button page. 
* Ensure disabled buttons render correctly.
* Ensure clicking a disabled link button performs no action.
* Ensure plaintext is legible in codeblocks.
fixes #3

Fix disabled button link.

---

CHANGELOG.md
src/components/Button/Button.js
src/components/Button/Button.test.js

Done:
- Correctly pass click events to buttons. Fixes: https://github.com/canonical-web-and-design/react-components/issues/20.

Fix button click events

---

.github/workflows/percy.yaml

Add config for percy -> storybook github action. 
Unfortunately, I think we have to merge this to see if this works!
Build details should appear [here](https://percy.io/vanilla-framework/react-components) after this runs.

Add percy github action config.

---

package.json
yarn.lock

Add @percy/storybook dependency.

Add @percy/storybook.

---

.gitignore

Generated when building locally.

Add storybook-static to gitignore.

---

CHANGELOG.md
HACKING.md
PUBLISH-NPM-PACKAGE.md
PUBLISHING-DOCS.md
README.md

Done:
- Updated readme with more detail. Fixes: https://github.com/canonical-web-and-design/react-components/issues/38.
- Add npm publish doc. Fixes: https://github.com/canonical-web-and-design/react-components/issues/10.
- Add GitHub Pages doc. Fixes: https://github.com/canonical-web-and-design/react-components/issues/9.
- Add a hacking doc. Fixes: https://github.com/canonical-web-and-design/react-components/issues/8.

Add project documentation

---

.gitignore
CHANGELOG.md
HACKING.md
package.json
src/components/Accordion/Accordion.js
src/components/Accordion/Accordion.stories.mdx
src/components/Accordion/Accordion.test.js
src/components/AccordionSection/AccordionSection.js
src/components/AccordionSection/AccordionSection.test.js
src/components/AccordionSection/__snapshots__/AccordionSection.test.js.snap

Done:
- Allow Accordion to have external state control.
- Add yarn commands for linking the package.
QA:
- Click on the demo link.
- Navigate to the docs for the Accordion.
- Click on the Docs tab and scroll to External state.
- The accordion should open and close (click "Show code" if you wish to see that it is using an external state hook).

Accordion external state

---

src/components/SearchAndFilter/SearchAndFilter.js
src/components/SearchAndFilter/SearchAndFilter.stories.mdx
src/components/SearchAndFilter/SearchAndFilter.test.js
src/components/SearchAndFilter/__snapshots__/SearchAndFilter.test.js.snap
src/components/SearchAndFilter/index.js

Run Storybook locally and view: http://localhost:60078/?path=/docs/searchandfilter--default-story

Add basic structure of Search and Filter component

---

src/components/SearchBox/SearchBox.js
src/components/SearchBox/__snapshots__/SearchBox.test.js.snap

Fixes https://github.com/canonical-web-and-design/juju-squad/issues/1325

Improve accessibility of search box

---

src/components/Chip/Chip.js
src/components/Chip/Chip.scss
src/components/Chip/Chip.stories.mdx
src/components/Chip/Chip.test.js
src/components/Chip/__snapshots__/Chip.test.js.snap
src/index.scss

Added the default Chip component.
Added styling to be ported to Vanilla framework
- Run `./run`
- Go to http://localhost:8403/?path=/story/chip--default-story
- See it looks :ok_hand: 
Fixes https://github.com/canonical-web-and-design/juju-squad/issues/1332

Add basic Chip pattern

---

src/components/Chip/Chip.js
src/components/Chip/Chip.scss
src/components/Chip/Chip.stories.mdx
src/components/Chip/Chip.test.js

Added dismiss UI to a Chip
- Run `./run`
- Go to http://localhost:8403/?path=/story/chip--dismissible
- Check it matches [the design](https://app.zeplin.io/project/5ed19809e42d2c9b901fcd9c/screen/5ed19897d3b87fb8faba02e4)
Fixes https://github.com/canonical-web-and-design/juju-squad/issues/1333

Add dismiss UI to chip

---

src/components/Chip/index.js
src/components/SearchAndFilter/FilterPanelSection/FilterPanelSection.js
src/components/SearchAndFilter/FilterPanelSection/FilterPanelSection.test.js
src/components/SearchAndFilter/FilterPanelSection/__snapshots__/FilterPanelSection.test.js.snap
src/components/SearchAndFilter/FilterPanelSection/filter-panel-section.scss
src/components/SearchAndFilter/FilterPanelSection/index.js
src/components/SearchAndFilter/SearchAndFilter.js
src/components/SearchAndFilter/SearchAndFilter.scss
src/components/SearchAndFilter/SearchAndFilter.stories.mdx
src/components/SearchAndFilter/SearchAndFilter.test.js
src/components/SearchAndFilter/__snapshots__/SearchAndFilter.test.js.snap

- http://localhost:65233/?path=/story/searchandfilter--external-state
Fixes https://github.com/canonical-web-and-design/juju-squad/issues/1327,
Fixes https://github.com/canonical-web-and-design/juju-squad/issues/1329

Add filter panel sections

---

src/components/SearchAndFilter/FilterPanelSection/FilterPanelSection.js
src/components/SearchAndFilter/FilterPanelSection/FilterPanelSection.test.js
src/components/SearchAndFilter/FilterPanelSection/__snapshots__/FilterPanelSection.test.js.snap
src/components/SearchAndFilter/FilterPanelSection/filter-panel-section.scss
src/components/SearchAndFilter/SearchAndFilter.js
src/components/SearchAndFilter/SearchAndFilter.stories.mdx

- Pull branch
- Resize window so that chips overflow
- Verify counter appears and disappears as expected
http://localhost:53721/?path=/story/searchandfilter--external-state

Add an overflow chip counter for filter panel

---

src/components/Chip/Chip.js
src/components/Chip/Chip.scss
src/components/Chip/__snapshots__/Chip.test.js.snap
src/components/SearchAndFilter/FilterPanelSection/FilterPanelSection.js
src/components/SearchAndFilter/FilterPanelSection/__snapshots__/FilterPanelSection.test.js.snap
src/components/SearchAndFilter/FilterPanelSection/filter-panel-section.scss
src/components/SearchAndFilter/SearchAndFilter.js
src/components/SearchAndFilter/SearchAndFilter.scss
src/components/SearchAndFilter/SearchAndFilter.stories.mdx
src/components/SearchAndFilter/SearchAndFilter.test.js
src/components/SearchAndFilter/__snapshots__/SearchAndFilter.test.js.snap
src/components/SearchAndFilter/shared.js

- http://localhost:53092/iframe.html?id=searchandfilter--external-state&viewMode=story
- Click chips in dropdown panel
- Dismiss chips from search box
- Click enough chips to overflow
Fixes https://github.com/canonical-web-and-design/juju-squad/issues/1308,
Fixes https://github.com/canonical-web-and-design/juju-squad/issues/1330

Add chips to search bar

---

Dockerfile
konf/site.yaml

Add dockerfile and konf/site.yaml, to enable new demoservice.

Add dockerfile and konf/site.yaml for demos

---

.github/workflows/cypress.yaml
.github/workflows/percy.yaml

Use 'main' branch in place of deprecated 'master' for github checkout action.
None, tests should pass.

Use main branch

---

.gitignore
.storybook/main.js
package.json
yarn.lock

- Add A11y Storybook plugin
- View Accessiblity tab in bottom panel for each component

Add A11y Storybook plugin

---

src/components/Chip/Chip.js
src/components/Chip/Chip.scss
src/components/Chip/Chip.test.js
src/components/Chip/__snapshots__/Chip.test.js.snap
src/components/Input/Input.js
src/components/Notification/Notification.js
src/components/SearchAndFilter/FilterPanelSection/FilterPanelSection.js
src/components/SearchAndFilter/FilterPanelSection/FilterPanelSection.test.js
src/components/SearchAndFilter/FilterPanelSection/__snapshots__/FilterPanelSection.test.js.snap
src/components/SearchAndFilter/FilterPanelSection/filter-panel-section.scss
src/components/SearchAndFilter/SearchAndFilter.js
src/components/SearchAndFilter/SearchAndFilter.scss
src/components/SearchAndFilter/SearchAndFilter.stories.mdx
src/components/SearchAndFilter/SearchAndFilter.test.js
src/components/SearchAndFilter/__snapshots__/SearchAndFilter.test.js.snap
src/components/SearchBox/SearchBox.js
src/components/SearchBox/SearchBox.scss
src/components/Select/Select.js
src/components/Textarea/Textarea.js
src/utils.js
src/utils.test.js

- Pull branch
- Click http://localhost:56916/iframe.html?id=searchandfilter--external-state&viewMode=story
- Search for known and unknown chips

Add search with pattern matching to search and filter

---

src/components/SearchAndFilter/SearchAndFilter.js
src/components/SearchAndFilter/SearchAndFilter.stories.mdx
src/components/SearchAndFilter/__snapshots__/SearchAndFilter.test.js.snap

Add returnSearchData function to default story
```shell
yarn start
```
- View `/?path=/story/searchandfilter--default-story`
- Should load without error

Add returnSearchData function to default story

---

src/components/ModularTable/ModularTable.scss
src/components/ModularTable/ModularTable.tsx

- This reverts commit 3e241b73ce1ac05a6bf788d6197e997590a39dca.

Revert "Fix u-hide override affecting expanding table headers"

---

CHANGELOG.md
package.json
src/components/Accordion/Accordion.test.tsx
src/components/AccordionSection/AccordionSection.test.tsx
src/components/AccordionSection/AccordionSection.tsx
src/components/AccordionSection/__snapshots__/AccordionSection.test.tsx.snap
src/components/ContextualMenu/ContextualMenu.tsx
src/components/Modal/Modal.js
src/components/Modal/Modal.test.js
src/components/Modal/__snapshots__/Modal.test.js.snap
src/setupTests.js
yarn.lock

- Replaced the uuid dep with nanoid.
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
- Run storybook and view the Accordion.
- Inspect the sections and they should have ids of random strings.
Fixes: canonical-web-and-design/react-components#319.
Fixes: canonical-web-and-design/react-components#55.

Replace uuid with nanoid

---

CHANGELOG.md
README.md
package.json
src/components/SearchAndFilter/FilterPanelSection/FilterPanelSection.js
src/components/SearchAndFilter/SearchAndFilter.js
src/components/SearchAndFilter/SearchAndFilter.scss
src/components/SearchAndFilter/SearchAndFilter.stories.mdx
src/components/SearchAndFilter/SearchAndFilter.test.js
src/components/SearchAndFilter/shared.js
yarn.lock

- Search and filter tweaks and bug fixes
- Added instructions on how to develop with project locally
```shell
yarn start
```
- View Search and Filter component in Storybook
- Verify that existingSearchData prop displays properly
- Check instructions in README on local development
- Try to run project locally in React project

Search and filter tweaks

---

src/components/SearchAndFilter/SearchAndFilter.js
src/components/SearchAndFilter/SearchAndFilter.stories.mdx

- Improve Storybook docs for SearchAndFilter
```shell
yarn start
```
View Search And Filter variations in Storybook

Improve docs for SearchAndFilter

---

.github/release-drafter.yml
.github/workflows/release-drafter.yml

- Adds release drafter config
- Adds release drafter GH workflow
- Unfortunately, needs to be merged to master to run, so no way to QA at this point (apart from comparing with configs from vanilla)

Add release drafter config

---

src/components/AccordionSection/AccordionSection.test.tsx
src/components/AccordionSection/AccordionSection.tsx
src/components/AccordionSection/__snapshots__/AccordionSection.test.tsx.snap

- Itemised list of what was changed by this PR.
Fixes #403 
- Review and test accordion examples:
- https://react-components-439.demos.haus/?path=/docs/accordion--default-story
- make sure they work as expected
- make sure they use new HTML structure, as per https://vanillaframework.io/docs/patterns/accordion
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```

Update accordion to new HTML structure

---

package.json

- Bumps version to 0.17.2 to release missing peer dependency
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
Fixes: # .

Bump version to v0.17.2

---

src/components/Card/Card.stories.mdx
src/components/Col/Col.stories.mdx
src/components/Col/Col.tsx
src/components/MainTable/MainTable.stories.mdx
src/components/Strip/Strip.stories.mdx

- Update more col sizes to numbers.

Update more col values to numbers

---

src/components/ActionButton/ActionButton.test.tsx
src/components/ContextualMenu/ContextualMenuDropdown/ContextualMenuDropdown.test.tsx
src/hooks/useThrottle.test.ts

- Updated fake timers to use modern Jest implementation
- N/A - tests should pass
Fixes #487

Update to using modern Jest fake timers

---

.github/labeler.yml

- Turn of auto adding QA/code needed labels.

Turn of auto adding QA/code needed labels

---

src/components/MainTable/MainTable.tsx

- Improve the MainTable types to correct some issues that were found when using with maas-ui.

Improve the MainTable types

---

src/components/Accordion/Accordion.tsx
src/components/ActionButton/ActionButton.tsx
src/components/ArticlePagination/ArticlePagination.tsx
src/components/Button/Button.tsx
src/components/Card/Card.tsx
src/components/Code/Code.tsx
src/components/CodeSnippet/CodeSnippet.tsx
src/components/Col/Col.tsx
src/components/ContextualMenu/ContextualMenu.tsx
src/components/Field/Field.tsx
src/components/Form/Form.tsx
src/components/Icon/Icon.tsx
src/components/Input/Input.tsx
src/components/Label/Label.tsx
src/components/Link/Link.tsx
src/components/List/List.tsx
src/components/MainTable/MainTable.tsx
src/components/Notification/Notification.tsx
src/components/Row/Row.tsx
src/components/SearchBox/SearchBox.tsx
src/components/Select/Select.tsx
src/components/Spinner/Spinner.tsx
src/components/Strip/Strip.tsx
src/components/SummaryButton/SummaryButton.tsx
src/components/Table/Table.tsx
src/components/TableCell/TableCell.tsx
src/components/Tabs/Tabs.tsx
src/components/Textarea/Textarea.tsx
src/components/Tooltip/Tooltip.tsx
src/types/index.ts

- Added `ClassName` type and used across all components with a `className` prop.
- N/A
Fixes #551

Use consistent type for className prop

---

src/components/ActionButton/ActionButton.tsx
src/components/Button/Button.tsx
src/components/Card/Card.tsx
src/components/CheckableInput/CheckableInput.tsx
src/components/CheckboxInput/CheckboxInput.tsx
src/components/ContextualMenu/ContextualMenu.tsx
src/components/ContextualMenu/ContextualMenuDropdown/ContextualMenuDropdown.tsx
src/components/Input/Input.tsx
src/components/Notification/Notification.tsx
src/components/RadioInput/RadioInput.tsx
src/components/SearchBox/SearchBox.tsx
src/components/Select/Select.tsx
src/components/Slider/Slider.tsx
src/components/Strip/Strip.tsx

- Fixed instances of prop spreading causing incorrect intersection types.
- Fixed button prop typing
- N/A
Fixes #543 
Fixes #546

Fix instances of prop spreading causing incorrect intersection types

---

src/components/ActionButton/ActionButton.tsx
src/components/ActionButton/__snapshots__/ActionButton.test.tsx.snap
src/components/Form/Form.tsx
src/components/List/List.tsx
src/components/Notification/Notification.tsx

- Fixed some more TypeScript issues that I've encountered while trying to upgrade to v0.19.0
- N/A

Fix more TypeScript bugs

---

src/components/Textarea/Textarea.test.tsx
src/components/Textarea/Textarea.tsx

- Allow input attributes on Textarea.
N/A
Fixes: #571.

Allow input attributes on Textarea

---

src/components/Tooltip/Tooltip.test.tsx
src/components/Tooltip/Tooltip.tsx

- Allow tooltip messages that contain HTML.
N/A

Allow tooltip messages that contain HTML

---

.github/workflows/test.yaml
src/components/ModularTable/ModularTable.stories.mdx

- Add inclusive naming action to workflows
- Ran the action to remove any language
- NOTE: Many cases of non-inclusive language could not be dealt with in this moment. An issue has been made to address in the future.
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
- Check the action works properly
- Check the language changes make lexical sense
Fixes: https://github.com/canonical-web-and-design/web-squad/issues/4456

Add and initial run of inclusive naming action

---

.eslintrc.js
src/components/ContextualMenu/ContextualMenu.test.tsx
src/components/Notification/Notification.test.tsx
src/components/Notification/Notification.tsx
src/components/Notification/__snapshots__/Notification.test.tsx.snap
src/components/Tabs/Tabs.test.tsx
src/components/Tabs/Tabs.tsx
src/components/Tabs/__snapshots__/Tabs.test.tsx.snap
src/components/Tooltip/Tooltip.test.tsx
src/components/Tooltip/Tooltip.tsx
src/types/index.ts

- Replaces `data-test` with `data-testid` to follow our conventions and updates eslint rules to enforce it.
Fixes #641 
Make sure all CI check pass.

Rename `data-test` to `data-testid` 

---

.circleci/config.yml
.github/workflows/release-drafter.yml
PUBLISH-NPM-PACKAGE.md
PUBLISHING-DOCS.md
README.md

Renamed any remaining references to `master` branch to new `main` branch.
- Review code changes
- Make sure any updated links work correctly

Rename all remaining references to master branch

---

renovate.json

Reuses renovate config from vanilla-framework repo for consistency

Use renovate config from vanilla-framework

---

.circleci/config.yml

- Update CircleCI image to use node LTS.
Make sure that CircleCi job (percy) passed

Update CircleCI docker image

---

src/components/Chip/Chip.stories.mdx
src/components/Chip/Chip.test.tsx
src/components/Chip/Chip.tsx

- Added colored chips.
- Check rendered [Chips](https://react-components-692.demos.haus/?path=/docs/chip--default-story) component.
- Run Chip tests.
Fixes: #691

Added colored chip

---

src/components/Spinner/Spinner.stories.mdx
src/components/Spinner/Spinner.test.tsx
src/components/Spinner/Spinner.tsx
src/components/Spinner/__snapshots__/Spinner.test.tsx.snap

- Added `role`, `aria-live` and `label` text to the spinner component
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
- Check the spinner with VoiceOver
Fixes: #590 .

Add aria attributes to spinner

---

src/components/AccordionSection/AccordionSection.tsx
src/components/CheckableInput/CheckableInput.tsx
src/components/ContextualMenu/ContextualMenu.tsx
src/components/Modal/Modal.tsx
src/hooks/useId.test.ts
src/hooks/useId.ts

- refactor: add useId hook
- We use a similar solution in MAAS UI: https://github.com/canonical-web-and-design/maas-ui/blob/master/ui/src/app/base/hooks/base.ts#L166
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
Fixes: # .

Refactor: add useId hook

---

src/components/Switch/Switch.stories.mdx
src/components/Switch/Switch.test.tsx
src/components/Switch/Switch.tsx
src/components/Switch/__snapshots__/Switch.test.tsx.snap
src/components/Switch/index.ts
src/index.ts

- Added new switch component with disabled example
- Wrote tests
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
Fixes: #712 .

Add switch component

---

src/components/CheckableInput/CheckableInput.test.tsx
src/components/CheckableInput/CheckableInput.tsx
src/components/Input/Input.test.tsx
src/components/Input/Input.tsx

- Add a class name and required to checkbox and radio button label elements.
N/A tests should pass.
Fixes: #716.

Add a class name and required to checkbox and radio button labels.

---

src/components/ModularTable/ModularTable.test.tsx

- refactor modular table to testing-library
- fix an issue where cells were rendered with no content (done by adding missing "accessor" to columns)
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
Fixes: # .

test: refactor modular table to testing-library

---

src/components/TableCell/TableCell.test.tsx
src/components/TableCell/__snapshots__/TableCell.test.tsx.snap

- migrate TableCell.test.tsx to testing-library
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
Fixes: # .

migrate TableCell.test.tsx to testing-library

---

src/components/MainTable/MainTable.tsx
src/hooks/index.ts
src/hooks/usePagination.test.ts
src/hooks/usePagination.ts

- add `usePagination` hook (source: https://github.com/canonical-web-and-design/maas-ui/pull/3684#discussion_r833927576)
- refactor MainTable to use the `usePagination` hook
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
Fixes: canonical-web-and-design/app-tribe#772

feat: add usePagination hook

---

src/components/Tabs/Tabs.test.tsx
src/components/Tabs/__snapshots__/Tabs.test.tsx.snap

- Migrate tabs tests to testing library
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
Fixes: # .

Tabs: Migrate tests to testing library

---

package.json
src/components/Badge/Badge.stories.mdx
src/components/Badge/Badge.test.tsx
src/components/Badge/Badge.tsx
src/components/Badge/index.ts

- A badge component is implemented.
- Open [the story book](https://react-components-796.demos.haus/?path=/story/badge--default-story).
- Verify the badge component is displayed and working properly. (for both badge types)
- Open "docs" page
- Verify the documentation done properly. 
Fixes: https://github.com/canonical-web-and-design/vanilla-squad/issues/1400

Create badge component

---

README.md

Update the org in the README as GitHub pages do not redirect.
Check the links work.

Update the org in the README

---

package.json
yarn.lock

- upgrade vanilla to v3.7.0
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
Fixes: # .

upgrade vanilla to v3.7.0

---

src/components/Col/Col.test.tsx
src/components/Col/__snapshots__/Col.test.tsx.snap

- Migrate Col to React Testing Library to prepare for React 18.
n/a

Migrate Col to RTL.

---

src/components/Row/Row.test.tsx
src/components/Row/__snapshots__/Row.test.tsx.snap

- Migrate Row to React Testing Library to prepare for React 18.
n/a

Migrate Row to RTL.

---

src/components/Strip/Strip.test.tsx
src/components/Strip/__snapshots__/Strip.test.tsx.snap

- Migrate Strip to React Testing Library to prepare for React 18.
n/a

Migrate Strip to RTL.

---

src/components/Spinner/Spinner.test.tsx
src/components/Spinner/__snapshots__/Spinner.test.tsx.snap

- Migrate Spinner to React Testing Library to prepare for React 18.
n/a

Migrate Spinner to RTL.

---

src/components/Label/__snapshots__/Label.test.tsx.snap
src/components/Link/Link.test.tsx
src/components/Link/__snapshots__/Link.test.tsx.snap

- Migrate Link to React Testing Library to prepare for React 18.
n/a

Migrate Link to RTL

---

src/components/ArticlePagination/__snapshots__/ArticlePagination.test.tsx.snap
src/components/Button/Button.test.tsx
src/components/Button/__snapshots__/Button.test.tsx.snap

- Migrate Button to React Testing Library to prepare for React 18.
n/a

Migrate Button to RTL.

---

src/components/Textarea/Textarea.test.tsx
src/components/Textarea/__snapshots__/Textarea.test.tsx.snap

- Migrate Textarea to React Testing Library to prepare for React 18.
n/a

Migrate Textarea to RTL.

---

src/components/Chip/Chip.test.tsx
src/components/Chip/Chip.tsx
src/components/Chip/__snapshots__/Chip.test.tsx.snap

- Migrate Chip to React Testing Library to prepare for React 18.
n/a

Migrate Chip to RTL.

---

src/components/SearchBox/SearchBox.test.tsx
src/components/SearchBox/SearchBox.tsx
src/components/SearchBox/__snapshots__/SearchBox.test.tsx.snap

- Migrate SearchBox to React Testing Library to prepare for React 18.
n/a

Update SearchBox to RTL.

---

src/components/Table/__snapshots__/Table.test.tsx.snap
src/components/TableHeader/TableHeader.test.tsx
src/components/TableHeader/__snapshots__/TableHeader.test.tsx.snap

- Migrate TableHeader to React Testing Library to prepare for React 18.
n/a

Migrate TableHeader to RTL.

---

src/components/Select/Select.test.tsx
src/components/Select/__snapshots__/Select.test.tsx.snap

- Migrate Select to React Testing Library to prepare for React 18.
n/a

Migrate Select to RTL.

---

src/components/TableRow/TableRow.test.tsx

- Migrate TableRow to React Testing Library to prepare for React 18.
n/a

Migrate TableRow to RTL.

---

src/components/Table/Table.test.tsx
src/components/Table/__snapshots__/Table.test.tsx.snap

- Migrate Table to React Testing Library to prepare for React 18.
n/a

Migrate Table to RTL.

---

src/components/Slider/Slider.test.tsx

- Migrate Slider to React Testing Library to prepare for React 18.
n/a

Migrate Slider to RTL.

---

src/components/Accordion/Accordion.test.tsx
src/components/Accordion/Accordion.tsx
src/components/Accordion/AccordionSection/AccordionSection.test.tsx
src/components/Accordion/AccordionSection/AccordionSection.tsx
src/components/Accordion/AccordionSection/__snapshots__/AccordionSection.test.tsx.snap
src/components/Accordion/__snapshots__/Accordion.test.tsx.snap

- Migrate Accordion and AccordionSection to React Testing Library to prepare for React 18.
n/a

Migrate Accordion to RTL

---

src/components/ActionButton/ActionButton.test.tsx
src/components/ActionButton/ActionButton.tsx
src/components/ActionButton/__snapshots__/ActionButton.test.tsx.snap

- Migrate ActionButton to React Testing Library to prepare for React 18.
n/a

Migrate ActionButton to RTL.

---

src/components/Card/Card.test.tsx
src/components/Card/Card.tsx
src/components/Card/__snapshots__/Card.test.tsx.snap

- Migrate Card to React Testing Library to prepare for React 18.
n/a

Migrate card to RTL

---

src/components/CheckboxInput/CheckableInput/CheckableInput.test.tsx
src/components/CheckboxInput/CheckableInput/CheckableInput.tsx

- Migrate CheckableInput to React Testing Library to prepare for React 18.
n/a

Migrate CheckableInput to RTL.

---

src/components/CodeSnippet/CodeSnippet.test.tsx

- Migrate CodeSnippet to React Testing Library to prepare for React 18.
n/a

Migrate Code to RTL.

---

src/components/ContextualMenu/ContextualMenu.test.tsx
src/components/ContextualMenu/ContextualMenu.tsx
src/components/ContextualMenu/ContextualMenuDropdown/ContextualMenuDropdown.test.tsx
src/components/ContextualMenu/ContextualMenuDropdown/ContextualMenuDropdown.tsx
src/components/ContextualMenu/ContextualMenuDropdown/__snapshots__/ContextualMenuDropdown.test.tsx.snap
src/components/ContextualMenu/__snapshots__/ContextualMenu.test.tsx.snap

- Migrate ContextualMenu to React Testing Library to prepare for React 18.
n/a

Migrate ContextualMenu to RTL.

---

src/components/Label/Label.test.tsx
src/components/Label/__snapshots__/Label.test.tsx.snap

- Migrate Label to React Testing Library to prepare for React 18.
n/a

Migrate Label to RTL.

---

src/components/List/List.test.tsx
src/components/List/__snapshots__/List.test.tsx.snap

- Migrate List to React Testing Library to prepare for React 18.
n/a

Migrate List to RTL.

---

src/components/Notification/Notification.test.tsx
src/components/Notification/Notification.tsx
src/components/Notification/__snapshots__/Notification.test.tsx.snap

- Migrate Notification to React Testing Library to prepare for React 18.
n/a

Migrate Notification to RTL.

---

src/components/PasswordToggle/PasswordToggle.test.tsx
src/components/PasswordToggle/PasswordToggle.tsx

- Migrate PasswordToggle to React Testing Library to prepare for React 18.
n/a

Migrate PasswordToggle to RTL.

---

src/components/Row/__snapshots__/Row.test.tsx.snap
src/components/SearchAndFilter/FilterPanelSection/FilterPanelSection.test.tsx
src/components/SearchAndFilter/FilterPanelSection/__snapshots__/FilterPanelSection.test.tsx.snap
src/components/SearchAndFilter/SearchAndFilter.test.tsx
src/components/SearchAndFilter/SearchAndFilter.tsx
src/components/SearchAndFilter/__snapshots__/SearchAndFilter.test.tsx.snap

- Migrate SearchAndFilter to React Testing Library to prepare for React 18.
n/a

Migrate SearchAndFilter to RTL.

---

.eslintrc.js

- Remove redundant eslint plugins
- make sure all CI checks pass

Remove redundant eslint plugins

---

PUBLISH-NPM-PACKAGE.md
package.json
prepare
prepare-release
src/components/MainTable/MainTable.test.tsx
src/components/MainTable/MainTable.tsx

Added a script to automate prep of new releases because I'm lazy and forgetful

Add script to automate the preparation of a new release

---

src/components/EmptyState/EmptyState.stories.mdx
src/components/EmptyState/EmptyState.test.tsx
src/components/EmptyState/EmptyState.tsx
src/components/EmptyState/index.ts
src/components/Icon/Icon.stories.scss
src/index.ts

- Added EmptyState component
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
- Check an usage example of the EmptyState component in the Storybook
Fixes: [WD-4257](https://warthogs.atlassian.net/browse/WD-4257).
[WD-4257]: https://warthogs.atlassian.net/browse/WD-4257?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add EmptyState component [WD-4257]

---

src/components/List/List.tsx

- Fix conflict between ListItem type and HTMLLIElement.

Fix ListItem content type conflict

---

package.json
yarn.lock

Updated to Vanilla 4.0
- Make sure all works fine

Update to Vanilla 4.0

---

src/components/Notification/Notification.stories.mdx

- added documentation for notification state handling
```shell
yarn start
```
- Check the storybook docs for Notification
Fixes: WD-5366

Add docs for the NotificationProvider, useNotify and NotificationConsumer

---

package.json

- Bump version to 0.41.1
- Review code

Prepare release 0.47.1

---

HACKING.md

- Add information on pull request conventional commits convention
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
Fixes: # .

docs: pr conventional commits convention

---

src/components/ContextualMenu/ContextualMenu.stories.mdx

- docs: fix contextual menu story
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
- Make sure the contextual menu story is rendered correctly.

docs: fix contextual menu story

---

package.json

Bump version to 0.47.2 for new release

chore: release 0.47.2

---

package.json

chore: release 0.47.3

---

.github/pull_request_template.md

- Added a "Percy steps" section to PR template, to aid Percy review.

fix(pr-template): add percy steps to template, to aid percy review

---

src/components/LoginPageLayout/LoginPageLayout.scss
src/components/LoginPageLayout/LoginPageLayout.stories.mdx
src/components/LoginPageLayout/LoginPageLayout.tsx
src/components/LoginPageLayout/index.ts
src/index.ts

- Added a new LoginPageLayout component from [Canonical/identity-platform-login-ui](https://github.com/Canonical/identity-platform-login-ui).
- Added storybook page with example usages.
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
- Navigate to LoginPageLayout component in the storybook
- Take a stab and try to break the component.
- No percy review needed, new screenshots will be taken.
Fixes: [WD-10995](https://warthogs.atlassian.net/browse/WD-10995)
[WD-10995]: https://warthogs.atlassian.net/browse/WD-10995?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Add LoginPageLayout component

---

HACKING.md
src/components/Field/Field.tsx
src/components/MultiSelect/MultiSelect.test.tsx
src/components/MultiSelect/MultiSelect.tsx

- Add some additional props to customise the MultiSelect for ReBAC Admin.

feat: add MultiSelect variations

---

src/components/TablePagination/TablePagination.scss
src/components/TablePagination/TablePagination.stories.tsx
src/components/TablePagination/TablePagination.tsx
src/components/TablePagination/TablePaginationControls/TablePaginationControls.test.tsx
src/components/TablePagination/TablePaginationControls/TablePaginationControls.tsx
src/components/TablePagination/__snapshots__/TablePagination.test.tsx.snap
src/components/TablePagination/utils.tsx
src/index.ts

- update TablePaginationControls to be used outside of TablePagination

refactor: update TablePaginationControls to be used outside of TablePagination

---

package.json

- include new build files.
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
Fixes: # .

fix: include new build files

---

src/components/Accordion/Accordion.tsx
src/components/Card/Card.stories.tsx
src/components/CodeSnippet/CodeSnippet.stories.tsx
src/components/Col/Col.stories.tsx
src/components/ContextualMenu/ContextualMenu.stories.tsx
src/components/ContextualMenu/ContextualMenu.tsx
src/components/ContextualMenu/ContextualMenuDropdown/ContextualMenuDropdown.tsx
src/components/MainTable/MainTable.tsx
src/components/Modal/Modal.stories.tsx
src/components/ModularTable/ModularTable.stories.tsx
src/components/Navigation/Navigation.tsx
src/components/SearchAndFilter/FilterPanelSection/FilterPanelSection.tsx
src/components/SearchAndFilter/SearchAndFilter.tsx
src/components/SearchAndFilter/utils.tsx
src/components/SideNavigation/SideNavigation.tsx
src/components/SideNavigation/SideNavigationLink/SideNavigationLink.stories.tsx
src/components/Slider/Slider.stories.tsx
src/components/Tabs/Tabs.test.tsx
src/components/Tooltip/Tooltip.stories.tsx
src/components/Tooltip/Tooltip.tsx
src/hooks/useOnEscapePressed.ts
src/hooks/useThrottle.ts
src/hooks/useWindowFitment.ts
src/index.test.ts
tsconfig.json

- Enable rule for disallowing implicit any.
- Add types for implicit any cases.

refactor: add types for implicit any cases

---

src/components/MainTable/MainTable.tsx

Adds a visually hidden label to the empty table header to resolve the accessibility error flagged by WAVE. This ensures the header is no longer considered empty while remaining visually hidden from users.
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
Fixes: # .

fix: add hidden text to resolve empty header accessibility error

---

src/components/Notifications/ToastNotification/Animate.tsx
src/components/Notifications/ToastNotification/Toast.scss
src/components/Notifications/ToastNotification/ToastNotification.stories.tsx
src/components/Notifications/ToastNotification/ToastNotificationList.tsx
src/components/Notifications/ToastNotification/ToastNotificationProvider.tsx

- Remove custom info icon
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```

fix: remove information icon customization

---

src/components/EventQueue/EventQueue.tsx
src/components/EventQueue/EventQueueProvider.test.tsx
src/components/EventQueue/index.ts
src/index.test.ts
src/index.ts

- Upstream event queue
- Add tests
Fixes: #[WD-19709](https://warthogs.atlassian.net/browse/WD-19709)
[WD-19709]: https://warthogs.atlassian.net/browse/WD-19709?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add event queue

---

src/components/Select/Select.test.tsx
src/components/Select/Select.tsx

- feat(select): expose help class name
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
- not needed

feat(select): expose help class name
