package.json
Remove `start` script from `package.json` as it fails due to there being no `public/` directory. This script is left over from the projects initialisation with [create-react-app](https://github.com/facebook/create-react-app) and is not intended for use on this project. Fixes #37.
- Clone this repo
- Run `yarn start`
- See that you get the following error: `error Command "start" not found.` indicating that there is no `start` script
=> Remove start script from package.json

package.json
Done:
- Only include the required files in the NPM package. Fixes: https://github.com/canonical-web-and-design/react-components/issues/23.
QA:
- Run `npm pack`.
- inspect the contents of the file (or read the output from `npm pack`).
- There shouldn't be any snapshots or test files.
=> Ignore files for NPM

src/components/Notification/Notification.js
- Fixed Notification timeout function not being executed, despite being provided timeout and close props.
- `yarn link` this project and `/node_modules/react` and link them in `maas-ui`.
- Go to <maas-ui-url>:8400/MAAS/r/account/prefs/details.
- Change your details and check that the notification closes after five seconds.
Fixes canonical-web-and-design/maas-ui#517
=> Fix Notification timeout function not being executed.

CHANGELOG.md, src/components/Button/Button.js, src/components/Button/Button.stories.mdx, src/components/Button/Button.test.js
Done:
- Add the dense option to the Button component. Fixes: https://github.com/canonical-web-and-design/react-components/issues/43.
QA:
- Run storybook and see that the Button component has a dense option.
=> Add dense buttons

.gitignore, package.json, src/components/SearchBox/SearchBox.js, src/components/SearchBox/SearchBox.stories.mdx, src/components/SearchBox/SearchBox.test.js
Done:
- Allow the search box to be controlled by external state.
QA:
- There's probably no easy way to QA this change without using the component. Make sure the component looks and functions as before.
Fixes #76
=> SearchBox external state control

src/components/Accordion/Accordion.js, src/components/Accordion/__snapshots__/Accordion.test.js.snap, yarn.lock
Done:
- Fix aria prop warning. Fixes: https://github.com/canonical-web-and-design/react-components/issues/74.
QA:
- Open storybook and navigate to the accordion page. You shouldn't get a warning about `Warning: Invalid ARIA attribute ariaMultiselectable`.
=> Fix warning about aria prop

CHANGELOG.md, src/components/Accordion/Accordion.js, src/components/Accordion/Accordion.test.js, src/components/AccordionSection/AccordionSection.js, src/components/AccordionSection/AccordionSection.test.js
Done:
- Add events when the Accordion sections are opened and closed.
QA:
- There's no really easy way to QA this without adding those props. See me if you want to QA this.
=> Add click events to Accordion

src/components/Tabs/Tabs.js, src/components/Tabs/Tabs.stories.mdx, src/components/Tabs/Tabs.test.js, src/components/Tabs/__snapshots__/Tabs.test.js.snap, src/components/Tabs/index.js
- Migrated [Tabs component from maas-ui](https://github.com/canonical-web-and-design/maas-ui/tree/master/ui/src/app/base/components/Tabs) with some modifications to make it more generic
- You can now give links a `component` prop in cases where you might want normal anchor links or react-router links
- Removed the `noBorder` prop - that's not in Vanilla and should just be handled by `listClassName` anyway
- Run `yarn docs` and check that the canvas and docs for Tabs are good
Fixes #150
=> Migrate Tabs component from maas-ui.

package.json, src/components/Tooltip/Tooltip.js, src/components/Tooltip/Tooltip.stories.mdx, src/components/Tooltip/Tooltip.test.js, src/components/Tooltip/__snapshots__/Tooltip.test.js.snap, src/components/Tooltip/index.js, yarn.lock
- Migrated [Tooltip component from maas-ui](https://github.com/canonical-web-and-design/maas-ui/tree/master/ui/src/app/base/components/Tooltip) with one modification to remove the custom `p-tooltip__message--portal` class and use an inline style instead.
- Added `react-useportal` dependency.
- Run `yarn docs` and check that there is a Tooltip page.
- Check that you can change the position property on the canvas.
- Check that the props are documented.
Fixes #151
=> Migrate Tooltip component from maas-ui.

CHANGELOG.md, src/components/Accordion/Accordion.js, src/components/Accordion/Accordion.stories.mdx, src/components/Accordion/Accordion.test.js, src/components/Accordion/__snapshots__/Accordion.test.js.snap, src/components/AccordionSection/AccordionSection.js, src/components/AccordionSection/AccordionSection.test.js, src/components/AccordionSection/__snapshots__/AccordionSection.test.js.snap
Vanilla 2.13 added an option to use headings in accordion titles.
This PR adds `titleElement` prop to the `Accordion` (and `AccordionSection`) components to enable this.
=> Add `titleElement` prop to accordion to support headings in titles

src/components/Select/Select.js, src/components/Select/Select.stories.mdx, src/components/Select/Select.test.js, src/components/Select/__snapshots__/Select.test.js.snap
- Add prop to pass the selected value to the parent for the Select component
- Go to `/?path=/docs/select--select` and see the new prop of the `Select` component
- See the state of the parent component is updated with the `value` of the selected option when the selection is changed
=> Add prop to pass the selected value to the parent for the Select 

src/components/Chip/Chip.js, src/components/Chip/Chip.stories.mdx, src/components/Chip/Chip.test.js, src/components/Chip/__snapshots__/Chip.test.js.snap
Added lead prop to chip to render lead-value chips.
*I switched from key-value as key it a reserved prop*
- Run `./run`
- Go to http://localhost:8403/?path=/story/chip--lead-value
- Check it looks like [the design](https://app.zeplin.io/project/5ed19809e42d2c9b901fcd9c/screen/5ed19897d3b87fb8faba02e4) _excluding the X action_
Fixes: https://github.com/canonical-web-and-design/juju-squad/issues/1334
=> Add lead-value chip

src/components/SearchAndFilter/SearchAndFilter.js, src/components/SearchAndFilter/SearchAndFilter.scss, src/components/SearchAndFilter/SearchAndFilter.test.js, src/components/SearchAndFilter/__snapshots__/SearchAndFilter.test.js.snap, src/components/SearchBox/SearchBox.js, src/components/SearchBox/__snapshots__/SearchBox.test.js.snap, src/index.scss
Add basic filter panel to Search and Filter component
- Fire up Storybook: http://localhost:65491/?path=/story/searchandfilter--default-story
- Click in input to activate panel
- Press Escape to close
- Click outside input or panel to close
Fixes https://github.com/canonical-web-and-design/juju-squad/issues/1335
=> Add basic filter panel to Search and Filter component

src/components/SearchAndFilter/FilterPanelSection/FilterPanelSection.js, src/components/SearchAndFilter/FilterPanelSection/FilterPanelSection.test.js, src/components/SearchAndFilter/FilterPanelSection/__snapshots__/FilterPanelSection.test.js.snap, src/components/SearchAndFilter/FilterPanelSection/filter-panel-section.scss
-Run Storybook
- View http://localhost:49435/iframe.html?id=searchandfilter--external-state
- Decrease screen size so overflow counter is shown
- Click overflow counter
- All chips should be shown
- Refresh page
- Navigate with keyboard, check counter can be activated with keyboard
=> Show overflow chips when counter is clicked

.babelrc, HACKING.md, package.json, tsconfig.json, yarn.lock
* Revert build to using `babel`, however also build ts/tsx with `@babel/preset-typescript`. 
* Generate type declarations for typescript files _only_.
=> Babel build with tsc declarations

src/components/Field/Field.js, src/components/Field/Field.test.js, src/components/Input/Input.js, src/components/Select/Select.js, src/components/Textarea/Textarea.js
- Update Field to support a React node to be supplied for the help prop.
- Update components that pass help to Field.
QA: None, tests should pass.
Fixes: https://github.com/canonical-web-and-design/react-components/issues/195.
Fixes: https://github.com/canonical-web-and-design/react-components/issues/67.
=> Allow a node to be passed to field help

CHANGELOG.md, src/components/Input/Input.js, src/components/Input/Input.test.js, src/components/Select/Select.js, src/components/Select/Select.test.js, src/components/Textarea/Textarea.js, src/components/Textarea/Textarea.test.js
- Updated Input, Select and Textarea to have a takeFocus prop which sets the focus to the input on first render.
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
- Add `setFocus` to a Story for each of Input, Select and Textarea.
- Run story book and open the docs tab for each component. The inputs should take focus.
Required by: https://github.com/canonical-web-and-design/maas-ui/issues/1469.
=> Allow form elements to take focus

.github/labeler.yml, .gitignore
- Add cypress videos and screenshots to gitignore.
- Add macos .DS_Store to gitignore.
- Add .gitignore to Maintenance labeller.
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
- n/a
Fixes: # .
=> chore: update gitignore with cypress artifacts.

README.md
Vanilla is built on sass, consequently any project using react-components must be configured to compile sass.
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
- n/a
Fixes: #262
=> doc: add sass-loader requirement

src/components/SearchBox/SearchBox.stories.mdx
Adds missing row to navigation in search example (`p-navigation__row--full-width`).
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
- Make sure SearchBox example in navigation renders correct navigation markup
=> Add missing row to navigation in search example

src/components/ModularTable/ModularTable.stories.mdx, src/components/ModularTable/ModularTable.tsx
- Makes sure ModularTable example correctly uses primitive table data and formats the cells in Cell components
- Updates Vanilla to 2.19 and uses new table cell icon class in examples
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
- Go to ModularTable story book page
- Make sure it renders correctly
- Make sure cells with icons have `p-table__cell--icon-placeholder` class names.
=> Update ModularTable examples

src/components/SearchAndFilter/SearchAndFilter.test.js, src/components/SearchAndFilter/__snapshots__/SearchAndFilter.test.js.snap, src/components/SearchBox/SearchBox.js, src/components/SearchBox/SearchBox.test.js
- Set the display name for SearchBox so that it does not appear as "ForwardRef".
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
No QA.
Fixes: #281
=> Set the component name for SearchBox.

src/components/ModularTable/ModularTable.scss, src/components/ModularTable/ModularTable.tsx
- Namespaced `ModularTable.scss` so that the `u-hide` override would not affect expanding tables.
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
- Run `yarn docs`
- Navigate to the MainTable > Expanding story
- Check that the table headers are correctly aligned with the content
=> Fix u-hide override affecting expanding table headers

CHANGELOG.md, src/components/Tooltip/Tooltip.stories.mdx, src/components/Tooltip/Tooltip.tsx, src/components/Tooltip/__snapshots__/Tooltip.test.tsx.snap
- Added classnames to the wrapping tooltip elements.
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
- View the Tooltip page in Storybook.
- Inspect an element that displays a tooltip. You should see classes applied to the wrapping elements.
Needed for: https://github.com/canonical-web-and-design/maas-ui/issues/1784.
=> Add classes to the wrapping tooltip elements.

src/components/Tooltip/Tooltip.tsx
As the Tooltip component allows you to control conditional rendering of the tooltip with the message prop, we should allow this to be explicitly assigned null.
This is useful when you are setting `message` in a ternary, e.g.
```ts
<Tooltip message={foo? "please render me": null} />
```
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
- n/a
Fixes: # .
=> fix: allow null assignment to tooltip message

package.json
- Added Vanilla as peer and dev dependencies.
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
- Use `yarn link` to test this with another project.
Fixes: #322 .
=> Make Vanilla a peer dependency

package.json, src/components/SearchAndFilter/FilterPanelSection/FilterPanelSection.js, src/components/SearchAndFilter/SearchAndFilter.js, src/components/SearchAndFilter/SearchAndFilter.scss, src/components/SearchAndFilter/__snapshots__/SearchAndFilter.test.js.snap, yarn.lock
- Decouple ContextualMenu / CSSTransition from Search And Filter
- Ensure panel stays open when clicking inside component
- ContextualMenu has grown far too complex to be used in this context. It also uses inline styles which make it very difficult to override when nested inside SearchAndFilter.
- CSSTransiton adds many levels of complexity and is also not compatible downstream when consumed by React projects in Strict mode.
```shell
yarn start
```
Fixes #320, Fixes #315 
- Go to search and filter pattern
- Ensure it displays and works as expected
=> Remove ContextualMenu / CSSTransition

src/components/SummaryButton/SummaryButton.scss, src/components/SummaryButton/SummaryButton.tsx, src/components/SummaryButton/__snapshots__/SummaryButton.test.tsx.snap
Removed unnecessary custom styling for the SummaryButton component, used Vanilla's `is-inline` button utility to achieve the same effect.
Run:
```shell
yarn start
```
Then visit http://localhost:8403:/?path=/story/summarybutton--default-story
- See that the SummaryButton component looks good across all screen widths
Fixes: #368  .
Before:
After:
=> Remove .p-summary__text scss

CHANGELOG.md, src/components/Icon/Icon.test.tsx, src/components/Icon/Icon.tsx
- Added `className` prop to the Icon component
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
- Check that storybook documents the Icon `className` prop
Fixes #329
=> allow custom classNames for Icon component

Dockerfile
Fixes demos by using `node-12` instead of `node`
Make sure demo is running: https://react-components-385.demos.haus/
=> Use node-12 in docker to fix demos

CHANGELOG.md, src/components/ActionButton/ActionButton.js, src/components/ActionButton/ActionButton.stories.mdx, src/components/ActionButton/__snapshots__/ActionButton.test.js.snap
- Updated `ActionButton` component to use `is-processing` class name instead of deprecated `is-active`
- Removed `p-action-button` class name from `ActionButton`, because it's not a class name provided by Vanilla
- Check storybook for ActionButton, make sure that examples work as expected
- https://react-components-384.demos.haus/?path=/docs/actionbutton--default-story
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
=> Update ActionButton button to use is-processing classname

CHANGELOG.md, src/components/Code/Code.js, src/components/Code/Code.stories.mdx, src/components/CodeSnippet/CodeSnippet.stories.mdx, src/components/CodeSnippet/CodeSnippetBlock.tsx
- Added support for multiple dropdowns to CodeSnippet component
- Updated storybook and docs
- Deprecated old Code component
- Review CodeSnippet docs https://react-components-390.demos.haus/?path=/docs/codesnippet--default-story
- make sure all examples render and work correctly
- Review Code docs https://react-components-390.demos.haus/?path=/docs/code--default-story
- make sure there is a deprecation note
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
Fixes: canonical-web-and-design/vanilla-squad#965
=> Add multiple dropdowns support to CodeSnippet component

CHANGELOG.md, src/components/ContextualMenu/ContextualMenu.tsx
- Adds support for `aria-pressed` in ContextualMenu to show recently added to Vanilla pressed button styles.
- Open ContextualMenu example, make sure that the button has pressed styles when menu is expanded:
- https://react-components-396.demos.haus/?path=/docs/contextualmenu--default-story#toggle
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
=> Add support for aria-pressed in ContextualMenu

CHANGELOG.md, src/components/MainTable/MainTable.js, src/components/MainTable/MainTable.stories.mdx, src/components/Table/Table.test.tsx, src/components/Table/Table.tsx, src/components/TableCell/TableCell.test.tsx, src/components/TableCell/TableCell.tsx, src/components/TableHeader/TableHeader.tsx, src/components/TableHeader/__snapshots__/TableHeader.test.tsx.snap
- removed `aria-sort` from tables that are not sortable
- removed unused `p-table--sortable`
- renamed `p-table-expanding` to `p-table--expanding`
- driveby: added state to expanding table examples, fixes #269
Fixes: #405
Fixes: #269
- Check table storybook to see if there are no regressions
- https://react-components-406.demos.haus/?path=/docs/maintable--default-story
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
=> Update table components to Vanilla 2.26

CHANGELOG.md, src/components/Tooltip/Tooltip.test.tsx, src/components/Tooltip/Tooltip.tsx, yarn.lock
- Removed inline `display: inline;` style from the tooltip components, and replaced it with the new `is-detached` utility class introduced by https://github.com/canonical-web-and-design/vanilla-framework/pull/3677
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
- Open the storybook [tooltip example](https://react-components-426.demos.haus/?path=/story/tooltip--default-story)
- Hover over the button, see that the tooltip appears and behaves as expected (compare to [live version](https://canonical-web-and-design.github.io/react-components/?path=/story/tooltip--default-story), there should be no differences) …
=> Update tooltip component to use new "is-detached" utility class

.github/workflows/publish-on-release.yml, .github/workflows/test.yaml
- Adds a GH workflow to publish to npm when GH release is published
No way to QA it other than trying it out with the next release once this is merged. Just a code review (comparing with Vanilla) needed.
=> Add automatic publish to npm workflow

.github/workflows/publish-on-release.yml
Our current script fails (due to some auth/404 issue), according to [this thread](https://github.com/npm/cli/issues/1637) adding explicit registry URL should help (we do it in Vanilla as well).
=> Add registry URL to release script

src/components/CodeSnippet/CodeSnippet.stories.mdx
- Change the only reference to deprecated `p-heading--two` to new `p-heading--2`
- Apparently prettier decided to reformat the whole file...
- Run storybook
- Check of code snippet examples render correctly
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
Fixes: #414
=> Fix reference to a deprecated heading class name

src/components/Code/Code.js, src/components/Code/Code.stories.mdx, src/components/Code/__snapshots__/Code.test.js.snap
- Update deprecated `Code` component to use `CodeSnippet` internally while keeping the legacy component API
Fixes: #372
- Open storybook for Code component: https://react-components-435.demos.haus/?path=/docs/code--default-story
- Make sure examples render as expected
- Make sure examples render CodeSnippet `p-code-snippet` instead of deprecated `p-code-numbered` or `p-code-copyable`
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
=> Update Code component to use CodeSnippet

src/components/CodeSnippet/CodeSnippet.stories.mdx, src/components/CodeSnippet/CodeSnippet.test.tsx, src/components/CodeSnippet/CodeSnippet.tsx, src/components/CodeSnippet/CodeSnippetBlock.tsx
- Added `content` prop to CodeSnippetBlock, allowing custom elements (like iframes) to be included in a snippet.
- Updated CodeSnippet to add a border when the `content` prop has been set on a block
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
- Open [demo](https://react-components-434.demos.haus/?path=/docs/codesnippet--content)
- See that the code snippet has a border and an iframe
- See that CI tests pass
Fixes: #419  .
=> Add `content` prop to CodeSnippetBlock

src/components/MainTable/MainTable.js, src/components/MainTable/MainTable.test.js
- Fixes how falsy keys are handled in MainTable
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
- Tests should pass
Fixes: #476
=> Fix handling of falsy values in keys in MainTable

src/components/MainTable/MainTable.stories.mdx, src/components/TableCell/TableCell.test.tsx, src/components/TableCell/TableCell.tsx
- Adds support for `has-overflow` in table cells
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
- Open demo https://react-components-498.demos.haus/?path=/docs/maintable--default-story#overflow
- Make sure contextual menus work well in table cells with overflow option
=> Allow overflowing content in table cells

src/components/Icon/Icon.test.tsx, src/components/Icon/Icon.tsx
- Added HTML props support to Icon component. I've used the `HTMLElement` generic because there isn't a dedicated one for `<i>` tags, but in other places (e.g. `JSX.IntrinsicElements["i"]`) they just use `HTMLElement` under the hood.
```shell
yarn start
```
- N/A - tests should pass
Fixes #492
=> Spread HTML props to Icon component

src/components/Accordion/Accordion.tsx, src/components/AccordionSection/AccordionSection.tsx, src/components/CheckableInput/CheckableInput.tsx, src/components/CheckboxInput/CheckboxInput.tsx, src/components/CodeSnippet/CodeSnippetDropdown.tsx, src/components/ContextualMenu/ContextualMenu.tsx, src/components/Icon/Icon.tsx, src/components/Modal/Modal.tsx, src/components/Pagination/Pagination.tsx, src/components/PaginationButton/PaginationButton.tsx, src/components/PaginationItem/PaginationItem.tsx, src/components/RadioInput/RadioInput.tsx, src/components/Slider/Slider.tsx, src/components/Spinner/Spinner.tsx, src/components/SummaryButton/SummaryButton.tsx, src/components/Table/Table.tsx, src/components/TableCell/TableCell.tsx, src/components/TableHeader/TableHeader.tsx, src/components/TableRow/TableRow.tsx, src/components/Tabs/Tabs.tsx, src/components/Tooltip/Tooltip.tsx
- Copy prop descriptions to type definitions.
- Export all prop types.
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
- Visit the following pages and check that they have descriptions in the descriptions column:
- [Accordion](url)
- [ContextualMenu](url)
- [Slider](url)
- [Tabs](url)
- [Tooltip](url)
Fixes: #274.
=> Show prop descriptions for typescript files

.storybook/preview-head.html
- Made default `prismjs` colour `unset`, which unsets Vanilla's default of black. I can't figure out why the syntax highlighting isn't properly working for stories that have an internal function for using hooks, but I think this is a bigger issue than just the syntax highlighting. For now at least the code is readable.
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
- Go to the MainTable - Expanding code block and check that there is no black text
Fixes #292
=> Fix some syntax highlighting being unreadable

package.json, yarn.lock
- Bump Vanilla to pre release that contains new notification styles for canonical-web-and-design/vanilla-framework#3818
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
- demo: https://react-components-513.demos.haus/
- check notifications - https://react-components-513.demos.haus/?path=/docs/notification--default-story
- they should have new style (legacy version of HTML)
=> Bump version of Vanilla to 2.33.0-rc1 pre-release

src/components/SearchAndFilter/FilterPanelSection/FilterPanelSection.js, src/components/SearchAndFilter/FilterPanelSection/FilterPanelSection.test.js, src/components/SearchAndFilter/FilterPanelSection/__snapshots__/FilterPanelSection.test.js.snap, src/utils.js, src/utils.test.js
A user reported that the search and filter component was causing the Juju Dashboard to crash because it was receiving invalid data. This makes the source of the problem, the `highlightSubString` function more resilient to bad data in an attempt to solve the issue.
- Use the search and filter UI, it should continue to work as normal
Fixes: #477
=> Graceful highlight

src/components/Chip/Chip.test.tsx, src/components/Chip/Chip.tsx, yarn.lock
- Replace the `cloud` on keyPress with `value` making this component generic
- Check the code
Fixes: https://github.com/canonical-web-and-design/react-components/issues/507
=> Replace the cloud key in Chip component

src/components/ContextualMenu/ContextualMenu.test.tsx, src/components/ContextualMenu/ContextualMenu.tsx, src/components/ContextualMenu/ContextualMenuDropdown/ContextualMenuDropdown.tsx, src/types/index.ts
- Allow null to be passed to optional ContextualMenu props. 
- Pass additional props to ContextualMenu subcomponents.
N/A.
Fixes: #377.
Fixes: #357.
=> ContextualMenu optional props

.babelrc, package.json, src/components/Accordion/Accordion.tsx, src/index.ts, tsconfig.json, yarn.lock
- Added `babel-plugin-moduler-resolver` package for absolute paths of the transpiled `.js` files
- Added `tsc-alias` package for absolute paths of the typescript declaration files
- Pull this branch
- Run `yarn build`
- Open `dist/components/Accordion/Accordion.d.ts` and check that the type imports are correctly transpiled to be relative
- Open `dist/components/Accordion/Accordion.js` and check that the `AccordionSection` import is correctly transpiled to be relative
Fixes #556
=> Set up absolute imports

src/components/Accordion/Accordion.tsx, src/components/ActionButton/ActionButton.tsx, src/components/ArticlePagination/ArticlePagination.tsx, src/components/Card/Card.tsx, src/components/CheckableInput/CheckableInput.tsx, src/components/Col/Col.tsx, src/components/ContextualMenu/ContextualMenu.tsx, src/components/Form/Form.tsx, src/components/Icon/Icon.tsx, src/components/Input/Input.tsx, src/components/Label/Label.tsx, src/components/Link/Link.tsx, src/components/MainTable/MainTable.tsx, src/components/Notification/Notification.tsx, src/components/Pagination/Pagination.tsx, src/components/Row/Row.tsx, src/components/SearchBox/SearchBox.tsx, src/components/Select/Select.tsx, src/components/Slider/Slider.tsx, src/components/Strip/Strip.tsx, src/components/Table/Table.tsx, src/components/TableCell/TableCell.tsx, src/components/TableHeader/TableHeader.tsx, src/components/TableRow/TableRow.tsx, src/components/Textarea/Textarea.tsx, src/index.ts, src/types/index.ts
- Added `PropsWithSpread` type that ensures that defined component props are never overwritten by a subsequent prop spread
- Added descriptions to some base types
- Pull this branch and open `SearchBox.tsx` in VSCode
- Hover over the props in the component function argument and check that the `onChange`, `onSubmit` and `value` props are typed according to the `Props` definition.
=> Add generic type for spreading props

src/components/Select/Select.test.tsx, src/components/Select/Select.tsx
- Allow Select to accept null for optional props.
N/A
Fixes: #570.
=> Allow Select to accept null for optional props.

src/components/Modal/Modal.test.tsx, src/components/Modal/Modal.tsx
- Add className prop to Modal and spread to the div.
N/A
Fixes: #565.
=> Add className prop to Modal

src/components/Icon/Icon.stories.mdx, src/components/Icon/Icon.tsx
Add social icons to Icon component
Check on Storybook that social icons appear https://react-components-592.demos.haus?path=/docs/icon--default-story
Check percy does not show any broken elements.
Fixes: https://github.com/canonical-web-and-design/react-components/issues/422
=> Add social icons to Icon component

.circleci/config.yml
Fixes [Circle CI certificate issue](https://github.com/nodesource/distributions/issues/1266) that was preventing CI checks building.
See that the checks pass.
=> Fix broken Circle CI certificates

src/components/Input/Input.test.tsx, src/components/Input/Input.tsx, src/components/Input/__snapshots__/Input.test.tsx.snap
- add `aria-invalid="true"` to Input when there's an error
- add tests
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
Fixes: #639 .
=> add aria-invalid to Input when there's an error

src/components/PasswordToggle/PasswordToggle.tsx
- Add new `type` prop to password toggle component
- Set default `type=button` to prevent the button submitting form
```shell
yarn start
```
- Add the`<PasswordToggle>` component to the <Form> and don't include a type. Check the form doesn't submit when the password toggle button is used. 
Fixes: #663
=> Prevent password toggle component submitting form

src/components/Input/Input.test.tsx, src/components/Input/Input.tsx
- Pass `required` to input element (currently it's only in the field component).
```shell
yarn start
```
- Check required exits on `input` element
Fixes: #638  .
=> Pass required to input element

src/components/SearchBox/SearchBox.stories.mdx
- Updated class names on the navigation example
```shell
yarn start
```
```shell
yarn build
npm pack
```
- The nav looks broken locally - checking it on the demo
Fixes: [#1167](https://github.com/canonical-web-and-design/vanilla-squad/issues/1167) .
=> Update navigation example

src/components/PaginationButton/PaginationButton.tsx
- Replaced `p-icon--contextual-menu` with `p-icon--chevron-down`
```shell
yarn start
```
- Check the pagination buttons https://react-components-675.demos.haus/?path=/story/pagination--default-story aren't broken 
Fixes: [#1168](https://github.com/canonical-web-and-design/vanilla-squad/issues/1168) .
=> Update pagination button to use new icon

src/components/Link/Link.stories.mdx, src/components/Link/Link.test.tsx, src/components/Link/Link.tsx
- Remove external link option from links
- Remove test
```shell
yarn start
```
- Check the external link example no longer exists
Fixes: #[1170](https://github.com/canonical-web-and-design/vanilla-squad/issues/1170) .
=> Remove external link

package.json
For the sake of renovate we specify the expected node versions in renovate.json, so specifying them in package.json is redundant and unnecessary.
https://github.com/canonical-web-and-design/vanilla-framework/blob/f28cda8560d24f67b14b0ccc93ae3303788a0736/renovate.json#L18-L20
Fixes canonical-web-and-design/vanilla-squad#1187
=> Remove specific node versions from package.json

src/components/SearchBox/SearchBox.stories.mdx
- The logo was using `p-navigation__link` instead of `p-navigation__item`. This fixes the padding.
```shell
yarn start
```
- Check this [demo](https://react-components-656.demos.haus/?path=/story/searchbox--navigation) which is using vanilla 3.0, check that changing the classname fixes the padding 
Fixes: #679
=> Fix extra padding in search box nav example

src/components/ContextualMenu/ContextualMenu.tsx
- Replace `p-icon--contextual-menu` with `p-icon--chevron-down`
```shell
yarn start
```
- Check this [demo](https://react-components-656.demos.haus/?path=/docs/maintable--overflow) and check the chevron appears when the classname is changed as mentioned above. I've QA'd this on the vanilla 3.0 branch and changing the classname here also fixes the [button](https://react-components-656.demos.haus/?path=/story/contextualmenu--toggle)
Fixes: [#4205](https://github.com/canonical-web-and-design/vanilla-framework/issues/4205) .
=> Replace p-icon--contextual-menu on table

src/components/List/List.stories.mdx
- Replace `p-label--new` with `p-label--positive`
```shell
yarn start
```
- See [here](https://react-components-656.demos.haus/?path=/story/list--stretch), the demo of 3.0 shows the label is broken. Change the classname to `p-label--positive` and see the correct label
Fixes: #682  .
=> Replace p-label--new

src/components/SearchAndFilter/SearchAndFilter.tsx
- Search query is wrapped with span tag with a class name `p-search-and-filter__search-query`.
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
- Open [demo](https://react-components-696.demos.haus/?path=/docs/search-and-filter--default-story#search-and-filter)
- Enter text to the default search and filter component.
- Verify the search term is bold.
- Verify search term has "p-search-and-filter__search-query" class.
Fixes: #616
=> Changed search term item's tag

src/components/Spinner/Spinner.test.tsx, src/components/Spinner/Spinner.tsx
- Spread <span> props on Spinner component
- This will allow adding an aria-label
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
- Add an aria-label to the spinner component and verify it's added to the outer span element correctly.
Fixes: #651 .
=> Spread <span> props on Spinner component

package.json, src/components/SummaryButton/SummaryButton.test.tsx, src/components/SummaryButton/__snapshots__/SummaryButton.test.tsx.snap, src/setupTests.js, tsconfig.json, yarn.lock
- add @testing-library/react
- Will help moving components from other canonical repos that already have tests written using @testing-library/react
- Will allow writing integration/unit tests focused on user experience (both developer and end user)
- Will allow for wider accessibility testing
- add @testing-library/jest-dom (for custom jest matchers, e.g. `.toBeInTheDocument`)
- refactor SummaryButton test with @testing-library as an example
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
Fixes: #705 .
=> Add @testing-library/react

src/components/CheckableInput/CheckableInput.test.tsx, src/components/CheckableInput/CheckableInput.tsx, src/components/CheckboxInput/CheckboxInput.stories.mdx, src/components/CheckboxInput/CheckboxInput.test.tsx, src/components/RadioInput/RadioInput.stories.mdx, src/components/RadioInput/RadioInput.test.tsx
- add inline prop support to checkbox & radio
related docs in vanillaframework.io:
- https://vanillaframework.io/docs/base/forms#inline-checkbox
- https://vanillaframework.io/docs/base/forms#inline-radio-button
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
Fixes: # .
=> feat: add inline prop support to checkbox & radio

.eslintrc.js, package.json, yarn.lock
- add eslint-plugin-testing-library
- rules that have existing violations in some react-components tests are set to "warn" instead of "error"
This will help follow testing-library best practices.
These violations aren't necessarily a real issue (except the single violation of "render" in "beforeEach").
We might want to leave them as is or update in a separate PR.
```
/react-components/src/components/Modal/Modal.test.tsx
64:16  warning  Avoid direct Node access. Prefer using the methods from Testing Library  testing-library/no-node-access
89:39  warning  Avoid direct Node access. Prefer using the methods from Testing Library  testing-library/no-node-access
93:40  warning  Avoid direct Node access. Prefer using the methods from Testing Library  testing-library/no-node-access
97:39  warning …
```
=> test: add eslint-plugin-testing-library

src/components/Spinner/Spinner.test.tsx, src/components/Spinner/Spinner.tsx, src/components/Spinner/__snapshots__/Spinner.test.tsx.snap
- fix: Spinner renders text twice
- Now text in the icon will only be rendered if no alternative text supplied (and act as a visually hidden description that's accessible for screen readers)
More details in the related issue #729 
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
Fixes:
- #729 
- canonical-web-and-design/app-tribe/issues/762
=> fix: Spinner renders text twice

src/components/ModularTable/ModularTable.stories.mdx, src/components/ModularTable/ModularTable.test.tsx, src/components/ModularTable/ModularTable.tsx
- Allow customisation of specific headers, rows and cells
- made possible with: `getHeaderProps`, `getRowProps` and `getCellProps` which resolve additional custom props for specific elements
- **[breaking change]** improve type safety (accessors)
Previously TypeScript would not complain about an invalid accessor string value. Now it expects not just a string, but a correct value for column accessors.
- before: `{ accessor: "disks", Header: "Disks",`
- after `{ accessor: "status" as const, Header: "Status" }`
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
Fixes: …
=> feat: customisation of specific headers, rows and cells in ModularTable

src/components/ModularTable/ModularTable.test.tsx, src/components/ModularTable/ModularTable.tsx
- refactor: remove ModularTable strict type https://github.com/canonical-web-and-design/react-components/pull/723/files#r828529359
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
Fixes: # .
=> refactor: remove ModularTable strict type

src/components/PaginationItem/PaginationItem.test.tsx, src/components/PaginationItem/PaginationItem.tsx, src/components/PaginationItem/__snapshots__/PaginationItem.test.tsx.snap
- Add `aria-current` to `Pagination Item` when it is active
- Add test for `aria-current`
- Update tests to use react testing library instead of jest 
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
- Click around and check nothing is broken
- Inspect the active button on the pagination docs, check `aria-current=page`
Fixes: #732
=> Add aria-current to Pagination Item

src/__mocks__/nanoid.ts, src/components/Accordion/Accordion.test.tsx, src/components/AccordionSection/AccordionSection.test.tsx, src/components/AccordionSection/__snapshots__/AccordionSection.test.tsx.snap, src/components/Field/Field.test.tsx, src/components/Field/Field.tsx, src/components/Form/Form.stories.mdx, src/components/Input/Input.test.tsx, src/components/Input/Input.tsx, src/components/Input/__snapshots__/Input.test.tsx.snap, src/components/PasswordToggle/PasswordToggle.test.tsx, src/components/PasswordToggle/PasswordToggle.tsx, src/components/Select/Select.test.tsx, src/components/Select/Select.tsx, src/components/Select/__snapshots__/Select.test.tsx.snap, src/components/Slider/Slider.test.tsx, src/components/Slider/Slider.tsx, src/components/Textarea/Textarea.test.tsx, src/components/Textarea/Textarea.tsx, src/components/Textarea/__snapshots__/Textarea.test.tsx.snap, src/setupTests.js
- Added aria labels to associate errors and help text to the field (some links to these roles in the issue: https://github.com/canonical-web-and-design/react-components/issues/725).
- Improved nanoid mock to avoid conflicts.
N/A no visual changes.
Fixes: #725.
=> Add error and help aria labels to form fields

src/components/Chip/Chip.test.tsx, src/components/Chip/Chip.tsx, src/components/Chip/__snapshots__/Chip.test.tsx.snap
- Spread props on non-dismissible chips.
- Prevent form submissions when chips are inside forms.
- Prevent className spread wiping the "p-chip" classes.
N/A not really possible (I linked react-components to maas-ui and testing with my in-progress branch).
Fixes: #739.
Fixes: #738.
Fixes: #737.
=> Improvements to the chip component.

src/components/Field/Field.tsx, src/components/Input/Input.stories.mdx, src/components/Input/Input.test.tsx, src/components/Input/Input.tsx, src/components/Input/__snapshots__/Input.test.tsx.snap
- align input help text for checkbox & radio to match the spec https://vanillaframework.io/docs/base/forms#help-text
- add help text examples to storybook
- migrate Input snapshot test to testing-library
- add `isTickElement` prop
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
- Verify that the help text is displayed correctly in different input types
Fixes: https://github.com/canonical-web-and-design/react-components/issues/748
=> fix: align input help text for checkbox & radio

cypress/integration/tooltip.spec.js, src/components/Tooltip/Tooltip.stories.mdx, src/components/Tooltip/Tooltip.test.tsx, src/components/Tooltip/Tooltip.tsx, src/components/Tooltip/__snapshots__/Tooltip.test.tsx.snap, src/components/Tooltip/index.ts
- fix Tooltip accessibility
- Tooltip child elements will now have a correct description attached via `aria-describedby`
- allowing clicking links within the tooltip
- fix focus handling (allowing to click elements within the tooltip and shifting focus via tab key appropriately)
- enable Tooltip component Storybook controls 
- migrate tests to @testing-library-react
- add integration tests
- add cypress test
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
- Make sure that you can access the link inside of the tooltip via tab and the button has a correct description via `aria-describedby`
Fixes: …
=> fix: tooltip accessibility

cypress/integration/tooltip.spec.js, package.json, src/components/Tooltip/Tooltip.tsx
- fix: tooltip on click should remain open until dismissed
- add cypress tests
- add missing default port number to cypress commands
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
- Check that the tooltip behaves as expected when activating on hover / keypress and can be dismissed
- You can use cypress test descriptions as a guidance
Fixes: https://github.com/canonical-web-and-design/react-components/issues/759
=> fix: tooltip on click should remain open until dismissed

src/components/Field/Field.tsx, src/components/Input/Input.stories.mdx, src/components/Input/Input.test.tsx, src/components/Input/Input.tsx
- allow custom help text class
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
Fixes: https://github.com/canonical-web-and-design/react-components/issues/760
=> feat: allow custom help text class

src/components/MainTable/MainTable.tsx
For the MainTable component: if `sortable` is false then [this onClick handler](https://github.com/canonical-web-and-design/react-components/blob/main/src/components/MainTable/MainTable.tsx#L166) evaluates to `false` too, with two consequences:
- React shows a warning because it's not a function
- When clicking a column header an error is thrown
(see [example](https://codesandbox.io/s/headless-monad-fg0lk5))
Changing the `condition && value` syntax into a conditional operator as suggested in the warning seems to solve it.
- Open demo or `dotrun`
- Check that the sortable MainTable behaves as usual
=> [MainTable] Use conditional operator in onClick 

src/components/Button/Button.stories.mdx, src/components/Button/Button.tsx, src/components/List/List.stories.mdx, src/components/StatusLabel/StatusLabel.stories.mdx, src/components/StatusLabel/StatusLabel.test.tsx, src/components/StatusLabel/StatusLabel.tsx, src/components/StatusLabel/index.ts, src/index.ts
- Add the Vanilla Label component. There is already a form Label component so this had to be StatusLabel.
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
- Visit the new StatusLabel storybook example (Edit: the demo service keeps timing out so you'll need to run this locally).
- Check that it appears like the Vanilla Label: https://vanillaframework.io/docs/patterns/labels
=> Add the Vanilla Label component.

src/components/List/List.tsx
- fix uneven middot spacing in a `List` component
- append a white space character at the end of each item if it's a `middot` list
CSS white space wrapping will prevent this space from being larger in case a component is already supplying items with a space appended to the end (2 spaces will be reduced to 1).
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
Fixes: https://github.com/canonical-web-and-design/app-tribe/issues/896
Fixes: https://github.com/canonical-web-and-design/react-components/issues/773
=> fix(List): uneven middot spacing

.babelrc, src/components/Navigation/Navigation.stories.mdx, src/components/Navigation/Navigation.test.tsx, src/components/Navigation/Navigation.tsx, src/components/Navigation/NavigationLink/NavigationLink.test.tsx, src/components/Navigation/NavigationLink/NavigationLink.tsx, src/components/Navigation/NavigationMenu/NavigationMenu.tsx, src/components/Navigation/index.ts, src/components/Navigation/types.ts, src/enums.ts, src/index.ts, src/types/index.ts, src/utils.ts
- Export the theme enum as a value.
- Update the Navigation types so that it's possible to generate links and buttons (before this PR it wasn't possible as you'd get errors about `onClick` events etc. for the wrong type of element.
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
If you wish you can QA that this does the right thing in maas-ui.
- Pull this PR and link the package.
- Pull the branch from https://github.com/canonical-web-and-design/maas-ui/pull/4022 and link react components.
- Run the ui and check that there are no type errors and the main nav is displayed.
Fixes: #783.
Fixes: #784.
=> Fix the Navigation types when generating links.

package.json
- Allow using react-components with React v18 as peer dependency.
- Review if code change in package.json is correct
=> Allow both React v17 and v18 as peer dependency

src/components/Navigation/Navigation.stories.mdx, src/components/Navigation/Navigation.test.tsx, src/components/Navigation/Navigation.tsx
- hide Navigation toggle when there are no items to display
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
- Open storybook and verify that the [navigation variant with no menu items](https://react-components-803.demos.haus/?path=/story/navigation--no-menu-items) does not display the menu toggle when resized to a mobile breakpoint
Fixes: https://github.com/canonical-web-and-design/maas-ui/issues/4049
=> fix: hide Navigation toggle when there are no items to display

.github/workflows/test.yaml, HACKING.md, PUBLISH-NPM-PACKAGE.md, PUBLISHING-DOCS.md, README.md, package.json, renovate.json, src/components/Loader/Loader.tsx, src/components/Notification/Notification.tsx
- fix Broken homepage link in NPM #619
- update all github urls to use canonical org
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
Fixes: #619 .
=> fix: Broken homepage link in NPM #619

src/components/Pagination/Pagination.test.tsx, src/components/Pagination/PaginationButton/PaginationButton.tsx, src/components/Pagination/PaginationItem/PaginationItem.tsx, src/components/Pagination/PaginationItem/__snapshots__/PaginationItem.test.tsx.snap
- update pagination buttons type to button
- this prevents default submit behaviour
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
Fixes: https://github.com/canonical/maas-ui/issues/4396
=> update pagination button type to button

src/components/Navigation/NavigationMenu/NavigationMenu.tsx, src/hooks/useClickOutside.test.tsx, src/hooks/useClickOutside.ts
- remove redundant id from useClickOutside
- this is redundant as verifying if the clicked element is the current element can be achieved by using ref only
This is safe to remove as it's only being used in react-components itself and [TagSelector](https://github.com/canonical/maas-ui/blob/5647d8ed12c1f8a547b7633d035c96be05e3e908/src/app/base/components/TagSelector/TagSelector.tsx) in maas-ui
https://github.com/search?q=org%3Acanonical+useClickOutside&type=code
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
- Go to the demo
- Verify that NavigationMenu opens and closes when clicking outside as before
Fixes: …
=> feat: remove redundant id from useClickOutside

src/components/ContextualMenu/ContextualMenu.test.tsx, src/components/ContextualMenu/ContextualMenu.tsx
- allow passing a node for ContextualMenu toggleLabel
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
Fixes: # .
=> feat(ContextualMenu): allow node label

src/components/ArticlePagination/ArticlePagination.test.tsx, src/components/ArticlePagination/__snapshots__/ArticlePagination.test.tsx.snap
- Migrate ArticlePagination to React Testing Library to prepare for React 18.
n/a
=> Migrate ArticlePagination to RTL.

src/components/ModularTable/ModularTable.stories.mdx, src/components/ModularTable/ModularTable.test.tsx, src/components/ModularTable/ModularTable.tsx, src/types/react-table-config.d.ts
- Added `useSortBy` plugin capabilities to the `ModularTable` component.
- Added `sortable` prop to the `ModularTable` component.
=> Feat: ModularTable now has the ability to use the useSortBy plugin.

src/components/Slider/Slider.tsx
Fixed Slider layout when the initial value is `0`
=> fix: Prevent Slider from breaking if default value is 0

src/components/Pagination/Pagination.stories.mdx, src/components/Pagination/Pagination.test.tsx, src/components/Pagination/Pagination.tsx, src/components/Pagination/__snapshots__/Pagination.test.tsx.snap
- Added a `centered` prop to the `Pagination` component
- Update the markup to the [current Vanilla pattern](https://vanillaframework.io/docs/patterns/pagination)
- Go to https://react-components-880.demos.haus/?path=/story/pagination--default-story
- Toggle the `centered` boolean and check that the pagination is centered when set to `true`
- Go to https://react-components-880.demos.haus/?path=/docs/pagination--default-story#centered
- Check that there is an example of centered pagination
=> Add centered prop to pagination component

src/components/List/List.test.tsx, src/components/List/List.tsx
Hello there! I hope you're doing great!
This PR is intended to fix DOM validation error for the stepped `List` with nested paragraphs.
**Related issues**: #875 #789 
Wrapper HTML element for the content of an item from `<p>` to `<div>`.
**Before changes**
```html
<ol class="p-stepped-list">
<li class="p-stepped-list__item">
<h3 class="p-stepped-list__title">Title and content as string</h3>
<p class="p-stepped-list__content">Content as string</p>
</li>
</ol>
```
**After changes**
```html
<ol class="p-stepped-list">
<li class="p-stepped-list__item">
<h3 class="p-stepped-list__title">Title and content as string</h3>
<div class="p-stepped-list__content">Content as string</div>
</li>
</ol>
```
After the change, when you provide one or several paragraphs as `content` it won't be an issue. …
=> fix(List): fix stepped list dom validation error for nested paragraphs

src/components/SearchBox/SearchBox.test.tsx, src/components/SearchBox/SearchBox.tsx
- Add an optional onClear prop and call it when clear button is clicked
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
- Type in the SearchBox component
- Provide a function for the `onClear` prop
- Make sure that the function is called when clicking on the reset button
=> Add onClear prop to SearchBox

.storybook/main.js
Seems like I found this fix [long time ago](https://github.com/storybookjs/storybook/issues/18876#issuecomment-1211644672) but somehow didn't push it back then?
Time to fix it now, that we updated storybook dependencies and it got broken again…
Go to storybook (https://react-components-889.demos.haus/?path=/story/accordion--default-story) and make sure Docs tab is available:
=> Fix storybook docs add-on

src/components/MainTable/MainTable.test.tsx, src/components/MainTable/MainTable.tsx
Added the option to add a hidden `caption` element to tables. This is to improve the experience for screen readers. See https://www.w3.org/WAI/tutorials/tables/caption-summary/
Check that the main table contains a `caption` element as the first child but that it is not visible on the screen
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
Fixes: #854 .
=> Add option for table captions

src/components/Tooltip/Tooltip.test.tsx, src/components/Tooltip/Tooltip.tsx
Added `zIndex` prop for the `Tooltip` component. Setting this property can be useful, for example, to allow a `Tooltip` to appear over an `l-aside` panel.
Fixes https://github.com/canonical/vanilla-framework/issues/4607.
=> Add zIndex prop for Tooltip component [WD-2282]

src/components/CheckboxInput/CheckboxInput.stories.mdx, src/components/RadioInput/RadioInput.stories.mdx
- Fixed two links that seem to be wrong on react-component [radio input](https://canonical.github.io/react-components/?path=/docs/radioinput--default-story) page and [checkbox input](https://canonical.github.io/react-components/?path=/docs/checkboxinput--default-story) page. 
Go to those page above in demo and click "Checkbox input" and "Radio input"
Fixes https://github.com/canonical/react-components/issues/904
=> Fix wrong links

src/components/Tooltip/Tooltip.test.tsx, src/components/Tooltip/Tooltip.tsx
- fix: render tooltip only when open
- this change removes the tooltip elements from the DOM when not open
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
- Open the demo
- Make sure the tooltip works exactly the same way as before
Fixes: https://github.com/canonical/react-components/issues/897
=> fix: render tooltip only when open

src/components/Tooltip/Tooltip.test.tsx, src/components/Tooltip/Tooltip.tsx
- Prevent clicks on the tooltip message from propagating to parent click handlers.
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
- Go to the tooltip stories and add `onClick={() => console.log("parent clicked")}` to the wrapping template div: https://github.com/canonical/react-components/blob/main/src/components/Tooltip/Tooltip.stories.mdx?plain=1#L20.
- Open storybook and go to the tooltip story.
- Hover the button and then click the tooltip or the link inside the tooltip.
- The "parent clicked" message should not get logged.
Fixes: #911.
=> Fix tooltip click propagation

src/components/Notification/Notification.tsx
- Make the wrapper tag for Notification title configurable. The default `h5` might disturb the heading hierarchy of the page.
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
- check that notifications still render the same as before
=> Notifications: allow override of title element, as the h5 might disturb the heading hierarchy

src/components/ContextualMenu/ContextualMenuDropdown/ContextualMenuDropdown.test.tsx, src/components/SearchAndFilter/SearchAndFilter.tsx, src/components/Tooltip/Tooltip.test.tsx, src/hooks/useWindowFitment.test.ts, src/hooks/useWindowFitment.ts
- Constrain the search and filter dropdown to stay within the viewport.
- View the search and filter dropdown [default story in isolation](https://react-components-906.demos.haus/iframe.html?args=&id=search-and-filter--default-story&viewMode=story).
- Click on the input to open the dropdown.
- Resize your window so that the entire dropdown doesn't fit.
- The dropdown should resize so that it doesn't get cut off and the contents should scroll.
Fixes: https://github.com/canonical/jaas-dashboard/issues/707.
=> Scroll the search and filter dropdown

src/components/MainTable/MainTable.stories.mdx, src/components/MainTable/MainTable.test.tsx, src/components/MainTable/MainTable.tsx
- When clicking a `MainTable` heading that is not sortable, we used to reset to no sorting. Fixed that.
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
- Try sorting a [main table](https://react-components-913.demos.haus/?path=/story/maintable--sortable) and click on headers that are sortable and not-sortable by. The network columns is not sortable and clicking it should not change the sort direction. This used to be broken before.
=> Fix table sorting

src/components/ModularTable/ModularTable.stories.mdx, src/components/ModularTable/ModularTable.test.tsx, src/components/ModularTable/ModularTable.tsx, src/types/react-table-config.d.ts
- Update ModularTable to support default sorting.
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
- Go to the modular table in storybook.
- Scroll down to the 'Sortable' example.
- Check that it is sorted by 'Build duration' by default.
=> Add default sort to ModularTable

src/components/SearchAndFilter/SearchAndFilter.test.tsx, src/components/SearchAndFilter/SearchAndFilter.tsx
- Added the following 2 optional callback props to the `SearchAndFilter` component:
1. `onPanelToggle`: triggered when the filter panel is shown/hidden.
2. `onExpandChange`: triggered when the search box has overflowing chips (= chips going new-line) and is expanded/collapsed.
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
- Add a `SearchAndFilter` component with the `onPanelToggle` prop set.
- Check that when clicking on the search box to show the filter panel and when clicking outside to hide it, the `onPanelToggle` function is called.
- Add a `SearchAndFilter` component with the `onExpandChange` prop …
=> [SearchAndFilter] add onPanelToggle and onExpandChange event handlers

src/components/Card/Card.tsx
- avoid broken reference to label on a card with no title
=> fix(card) avoid aria-labelledby reference when no title is passed

src/components/Tooltip/Tooltip.tsx, src/components/Tooltip/__snapshots__/Tooltip.test.tsx.snap
- avoid setting aria ref from tooltip anchor when the tooltip is not rendered
=> fix(tooltip) avoid broken reference to tooltip when not mounted

src/components/ConfirmationButton/ConfirmationButton.stories.mdx, src/components/ConfirmationButton/ConfirmationButton.test.tsx, src/components/ConfirmationButton/ConfirmationButton.tsx, src/components/ConfirmationButton/index.ts, src/components/ConfirmationModal/ConfirmationModal.stories.mdx, src/components/ConfirmationModal/ConfirmationModal.test.tsx, src/components/ConfirmationModal/ConfirmationModal.tsx, src/components/ConfirmationModal/index.ts, src/components/Modal/Modal.stories.mdx, src/index.ts
- Added ConfirmationModal component
- Added ConfirmationButton component
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
- Check an usage example of the 2 new components in the Storybook
Fixes: [WD-4255](https://warthogs.atlassian.net/browse/WD-4255).
[WD-4255]: https://warthogs.atlassian.net/browse/WD-4255?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add ConfirmationModal and ConfirmationButton components [WD-4255]

src/components/ActionButton/ActionButton.tsx
- reset height and width after loading finished on the ActionButton
- it used to leak setting height and width on load and keeping it set in the dom
=> fix(ActionButton) reset height and width after loading finished

package.json, src/components/ContextualMenu/ContextualMenu.tsx, src/components/Notification/Notification.tsx, src/components/NotificationProvider/NotificationProvider.test.tsx, src/components/NotificationProvider/NotificationProvider.tsx, src/components/NotificationProvider/__snapshots__/NotificationProvider.test.tsx.snap, src/components/NotificationProvider/index.ts, src/components/NotificationProvider/messageBuilder.tsx, src/components/NotificationProvider/types.ts, src/index.ts, yarn.lock
- Added NotificationProvider.
- Allows to trigger messages with the `const notify = useNotify();` hook easily, like  `notify.success("The thing finished` or `notify.failure("the thing failed", exception)`.
- Added a convenient `<NotifyConsumer>`, that can be placed anywhere and will render any triggered notification. This can be placed flexibly on top of a form, in a modal or used in an overlay.
Fixes: [WD-4256](https://warthogs.atlassian.net/browse/WD-4256)
[WD-4256]: https://warthogs.atlassian.net/browse/WD-4256?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add notification provider WD-4256

src/components/Pagination/Pagination.stories.mdx, src/components/Pagination/Pagination.test.tsx, src/components/Pagination/Pagination.tsx, src/components/Pagination/PaginationButton/PaginationButton.test.tsx, src/components/Pagination/PaginationButton/PaginationButton.tsx, src/components/Pagination/PaginationButton/__snapshots__/PaginationButton.test.tsx.snap, src/components/Pagination/__snapshots__/Pagination.test.tsx.snap
- Added Buttons-only Pagination for the case when total number of items is unknown. This use-case is required for the Audit logs feature in Juju Dashboard.
- Fully backwards compatible with all previous uses of Pagination component.
- Open storybook locally and navigate to the Pagination docs.
=> feat: Buttons-only Pagination

HACKING.md
- Added additional documentation to `HACKING.md` to explain step by step how linking with `yarn 3` should be done.
- Fixes: #953
=> fix: Add documentation for linking with yarn 3

HACKING.md, src/components/ModularTable/ModularTable.test.tsx, src/components/ModularTable/ModularTable.tsx
- When sorting is disabled for a specific column and/or there is no text being rendered within the column header, the column shouldn't have an aria-sort attribute and clicking on the respective column header won't trigger any sorting action.
- Fixes: #946
=> fix: Remove conditionally the aria-sort attribute and ability to sort from ModularTable

src/components/CodeSnippet/CodeSnippet.stories.mdx, src/components/CodeSnippet/CodeSnippet.test.tsx, src/components/CodeSnippet/CodeSnippetBlock.tsx
- Support a `ReactNode` as the value of the code to display in CodeSnippet.
https://warthogs.atlassian.net/browse/WD-5870
=> Support ReactNode in the CodeSnippet component.

src/components/ContextualMenu/ContextualMenu.tsx, src/components/ContextualMenu/ContextualMenuDropdown/ContextualMenuDropdown.test.tsx, src/components/ContextualMenu/ContextualMenuDropdown/ContextualMenuDropdown.tsx
- Add a prop to handle scrolling the contextual menu if it doesn't fit on the screen (handled in the same way as the search and filter dropdown: https://github.com/canonical/react-components/pull/906).
- Open `src/components/ContextualMenu/ContextualMenu.stories.mdx`.
- Scroll down to the "Toggle" story and duplicate the links objects so that there are quite a few links.
- add `scrollOverflow: true,` to the args.
- Run Storybook (`yarn start`).
- Open `<storybook-url>/iframe.html?id=contextualmenu--toggle&viewMode=story`
- Click on the button to open the menu.
- Resize your window so that the menu doesn't fit on the screen.
- The menu should resize so that it doesn't get cut off, and the content should scroll.
=> Contextual menu scrolling

.github/workflows/publish-docs.yml, .github/workflows/publish-on-release.yml, PUBLISH-NPM-PACKAGE.md
- Separate the workflow for publishing the docs on release, so that when it is manually run it doesn't also publish the package to NPM.
=> Separate docs workflow

.github/workflows/publish-docs.yml
- Add token permissions (as per the [docs](https://github.com/actions/deploy-pages)) for deploying to pages, as the previous job [failed](https://github.com/canonical/react-components/actions/runs/6034670898/job/16373781625).
=> Add permissions for deploying to pages.

src/components/Pagination/Pagination.test.tsx, src/components/Pagination/Pagination.tsx
- fixed pagination edge case for when the `totalPages +1 = truncateThreshold` to avoid duplicating the button for the first or last page
- See tests are valid and passing
=> Avoid duplicate first or last page button, when total pages is one above truncateThreshold

src/components/Modal/Modal.test.tsx, src/components/Modal/Modal.tsx
- Pressing Esc key closes the `Modal` instead of throwing a console error.
- This PR fixes the same issue in `ConfirmationModal`.
- Open any `Modal` in Storybook and then press Esc key.
- The `Modal` should close with no error shown in developer console.
Fixes: #973
=> fix: Pressing Esc key closes Modal

.github/workflows/pr-lint.yml
This PR adds a PR Lint action that enforces conventional commits convention for pull request titles. 
- ci: add pr lint
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
Fixes: # .
=> ci: Add PR linting

renovate.json
Renovate has [deprecated](https://docs.renovatebot.com/config-presets/) extending `renovate.json` and now requires extending a `default.json`.
I've changed this repo to use the apps default.json (which is pretty much the same as the vanilla config) as the Vanilla repo only has a renovate.json.
=> ci: Extend from a default config

package.json, src/components/Tooltip/Tooltip.test.tsx, src/components/Tooltip/Tooltip.tsx, yarn.lock
- Add delay of 500ms before showing tooltip after mouseover
- Delay is configurable from Props
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
Fixes: #975  .
=> feat: Add tooltip delay(500ms by default) after mouseover

src/components/Field/Field.test.tsx, src/components/Input/Input.test.tsx, src/components/Input/Input.tsx
This PR modifies the Input component to automatically generate and assign a unique id when one is not provided. This ensures correct label-input association as per accessibility standards.
- fix: input label without specifying id
- replace instances of soon-to-be-deprecated `.toHaveErrorMessage` with `.toHaveAccessibleErrorMessage`
Fixes: https://github.com/canonical/react-components/issues/1011
=> fix: input label without specifying id

src/components/TablePagination/TablePagination.scss, src/components/TablePagination/TablePagination.stories.mdx, src/components/TablePagination/TablePagination.test.tsx, src/components/TablePagination/TablePagination.tsx, src/components/TablePagination/TablePaginationControls/TablePaginationControls.test.tsx, src/components/TablePagination/TablePaginationControls/TablePaginationControls.tsx, src/components/TablePagination/TablePaginationControls/__snapshots__/TablePaginationControls.test.tsx.snap, src/components/TablePagination/TablePaginationControls/index.ts, src/components/TablePagination/__snapshots__/TablePagination.test.tsx.snap, src/components/TablePagination/index.ts, src/index.ts
- upstream the pagination component used for all tables from the lxd-ui project.
- Go to http://localhost:9009/?path=/docs/tablepagination--docs
- Check pagination functionality of the component and styling
- Check if documentation is clear for the usage of the component
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
=> feat: upstream generic pagination component for tables [WD-4258]

src/components/Modal/Modal.tsx
The modal opens with the content scrolled (when there's enough content to be scrollable), so the user can't read from the beginning. It seems like this behaviour was introduced in [this commit](https://github.com/canonical/react-components/commit/6633f75a53f04114ec64435259c2017f2c435358), where the focus is moved to one of the buttons on the footer.
Focus without scrolling into view. 
- `dotrun`
- Go to the `Modal` component in storybook
- Resize window till the modal becomes scrollable (or add some text to make it more obvious)
- Check that when the modal is opened the scrollbar is on top 
Fixes: #958
=> fix(modal): do not scroll content when opened

.github/workflows/publish-docs.yml
- fix issue with publishing doc workflow failing
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
- Publish doc workflow should successfully publish to github pages
=> fix: resolve issue with publish doc workflow

README.md
Removes separate Cypress badge as cypress is part of a single CI workflow.
- docs: remove cypress badge
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
Fixes: # .
=> docs: remove cypress badge

.github/labeler.yml, .github/workflows/labeler.yml
- The labeler action v5 update had config structure change which is breaking ci for forked PRs since it runs on pull_request_target. This PR adjusts the labeler action setup based on its official [documentation](https://github.com/actions/labeler/tree/main#pull-request-labeler)
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
=> ci: fix config structure change with labeler v5 update

.github/workflows/test.yaml, HACKING.md
- updated HACKING.md to include information for semantic-release.
- 
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
``
=> docs: update HACKING.md with information for semantic-release

src/components/MultiSelect/FadeInDown/FadeInDown.scss, src/components/MultiSelect/FadeInDown/FadeInDown.test.tsx, src/components/MultiSelect/FadeInDown/FadeInDown.tsx, src/components/MultiSelect/FadeInDown/index.ts, src/components/MultiSelect/MultiSelect.scss, src/components/MultiSelect/MultiSelect.stories.tsx, src/components/MultiSelect/MultiSelect.test.tsx, src/components/MultiSelect/MultiSelect.tsx, src/components/MultiSelect/index.ts, src/index.ts
This PR adds a component that already has been implemented in [maas-react-components](https://canonical.github.io/maas-react-components/?path=/docs/components-multiselect--docs). It seems that at least one other project needs this, which means it's time to upstream it to `react-components`
- feat: add multiselect component
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
- Go to MultiSelect component page in storybook
- Ensure you can open and close all variants without issues
=> feat: add multiselect component

src/components/ContextualMenu/ContextualMenu.stories.mdx
- Adds correct import of default exported `<Button />` component on `<ContextualMenu />`
- Run the project
- Open ContextualMenu stories
- Check that `Child element` example is now fixed
- Click on button of `Child function`
- Check that it doesn't break anymore
Fixes: #1033
=> fix: correctly import Button component on ContextualMenu story

src/components/TablePagination/TablePagination.stories.mdx, src/components/TablePagination/TablePagination.test.tsx, src/components/TablePagination/TablePagination.tsx, src/components/TablePagination/TablePaginationControls/TablePaginationControls.test.tsx, src/components/TablePagination/TablePaginationControls/TablePaginationControls.tsx, src/components/TablePagination/TablePaginationControls/__snapshots__/TablePaginationControls.test.tsx.snap, src/components/TablePagination/utils.tsx
- Introduced externally controlled mode for the `TablePagination` component
- added test for externally controlled mode for the `TablePagination` component. You can refer to the test for example usage in externally controlled mode.
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
- Check in projects that uses `TablePagination` if server pagination works.
=> feat: implement externally controlled mode for TablePagination [WD-8505]

src/components/TablePagination/TablePaginationControls/TablePaginationControls.tsx, src/components/TablePagination/__snapshots__/TablePagination.test.tsx.snap, src/components/TablePagination/utils.tsx
- Fixed description text adjustment for small screen sizes. removed unnecessary `useEffect` dependencies that was previously causing weird render cycle issues.
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
- On story book, try vary the screen size while looking at the `TablePagination` component. The pagination description (left of controls) should show `X out of Y` for small screen sizes consistently.
[Screencast from 07-02-2024 15:27:57.webm](https://github.com/canonical/react-components/assets/151511568/f398a660-aa87-4623-ba1a-6ba3a15e7c92)
=> fix: table pagination description adjustments for all screen sizes

src/components/TablePagination/utils.tsx
- Table pagination description should shrink based on its container width and not screen width. This was implemented before but was removed from a previous commit. This PR added the code back which implements the aforementioned logic.
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
- Go to `TablePagination` component in Storybook and inspect that the pagination description to show `X out of Y` before small screen breakpoint (~830px)
=> fix: revert change for table pagination text adjustment on small screen

src/components/TablePagination/TablePagination.scss
Even in its shortened version, the description for the table pagination goes new line multiple times on small widths:
To solve this, the description element is now hidden when width is below the small breakpoint.
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
- On any storybook example for the table pagination, resize the window so that the width is lower than 620px (small breakpoint).
- Check that the description is hidden.
=> fix: hide description when width is below the small breakpoint

src/components/Input/Input.tsx, src/components/Input/__snapshots__/Input.test.tsx.snap, src/components/TablePagination/TablePaginationControls/__snapshots__/TablePaginationControls.test.tsx.snap, src/components/TablePagination/__snapshots__/TablePagination.test.tsx.snap
- do not set `aria-describedby` attribute for the Input component if there is no help or success validation text.
- do not render label element for `CheckableInput` if input label is empty. This resolves the issue of potentially creating labels with no text content.
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
- Adjust the `help` and `success` props for the Input component on Storybook and make sure that the `aria-describedby` attribute is not set if both props are undefined.
- Pass empty string for the `label` prop for `RadioInput` and `CheckboxInput` components and make sure there is no empty `label` …
=> fix: address a11y issues in input related components

src/components/Col/Col.stories.mdx
- Fixed a typo
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
Fixes: # .
=> docs: Update Col component size in Col.stories

package.json, yarn.lock
- Added missing lodash/isequal dep that is required by NotificationProvider.
Fixes: #990.
=> fix(deps): Added missing lodash/isequal dep

src/components/NotificationProvider/NotificationProvider.test.tsx, src/components/NotificationProvider/NotificationProvider.tsx, src/components/NotificationProvider/__snapshots__/NotificationProvider.test.tsx.snap, src/components/NotificationProvider/messageBuilder.tsx, src/components/NotificationProvider/types.ts
- Allow to (optionally) customise the title for a success notification when using the `NotificationProvider`.
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
- Set a custom title for the success notification, and check that it is correctly displayed.
=> fix(notif-provider): make success notification title customisable

package.json, src/components/Icon/Icon.stories.scss, src/components/MultiSelect/MultiSelect.scss, yarn.lock
- Updates Vanilla to 4.9.0
- Removes problematic `@includes` (`vf-base` and `vf-b-forms`) and`@extend` uses from `MultiSelect.scss` and replaces them with copies of relevant parts of Vanilla.
This is a temporary solution until we find better ways to reuse bigger parts of Vanilla styling. `@extend` usage by itself is not huge issue, but it does silently create a duplicate of Vanilla styling.
Bigger problem was including `vf-base` and `vf-lists` (which contain required placeholders to extend) as they duplicate big chunks of Vanilla styling creating source order conflicts of old and new styles and breaking the styling of some other components.
- Check if MultiSelect renders and works as expected:
- https://react-components-1052.demos.haus/?path=/docs/multiselect--docs
- Check if previously …
=> fix(MultiSelect): Apply a temporary fix for Vanilla includes in MultiSelect component

HACKING.md, package.json, src/components/Card/Card.stories.tsx, src/components/FormikField/FormikField.stories.tsx, src/components/FormikField/FormikField.test.tsx, src/components/FormikField/FormikField.tsx, src/components/FormikField/index.ts, src/components/Input/Input.test.tsx, src/components/Input/Input.tsx, src/components/TablePagination/TablePaginationControls/__snapshots__/TablePaginationControls.test.tsx.snap, src/components/TablePagination/__snapshots__/TablePagination.test.tsx.snap, src/index.ts, yarn.lock
- upstream the FormikField component to make react-component's fields and Formik easier to work with. This component is already in use in maas-ui and react-components and we want to use it in another project.
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
- Go to the FormikField docs page in Storybook.
- Check that the docs make sense.
https://warthogs.atlassian.net/browse/WD-9813
Fixes: #957.
=> feat: upstream FormikField

src/components/ConfirmationModal/ConfirmationModal.test.tsx, src/components/ConfirmationModal/ConfirmationModal.tsx, src/components/Modal/Modal.test.tsx, src/components/Modal/Modal.tsx
- Stopped click event propagation when closing `Modal` and when closing or confirming `ConfirmationModal`.
- Check that `Modal` and `ConfirmationModal` renders as expected in storybook.
- (optional) For example, the stop click event propagation can be tested in Juju Dashboard when opening the charm actions panel of a charm and clicking on an action. A `ConfirmationModal` will be rendered in a `Portal`. Clicking the close button used to close the panel, but, using the changes in this PR, it doesn't.
- Fixes: #1032 
- https://warthogs.atlassian.net/browse/WD-9915
=> fix: stop click event propagation in Modal

src/components/Tooltip/Tooltip.tsx
- Fix tooltip open/close: When tooltip wraps multiple children, and we change which child is hovered, the tooltip should stay open.
see description video in https://github.com/canonical/anbox-cloud-dashboard/pull/732#pullrequestreview-1976424478
=> fix: tooltip open

.github/labeler.yml, .github/workflows/pr-labels.yml
- Adds a CI check that enforces Percy review and adding `Review: Percy +1` label.
- Adds a `Review: Percy needed` automatically if any files in `src` are changed.
- Check that there is no `Review: Percy +1` label on the PR.
- Check that CI is failing on "PR Percy Review Label Required" job
- Find a bot comment describing why merging is blocked that describes what to do
- Follow the comment instructions
- After reviewing Percy, add `Review: Percy +1` label
- Make sure CI passes
=> ci: Require the review of Percy visual tests

src/components/Field/Field.test.tsx, src/components/Field/Field.tsx, src/components/FormikField/FormikField.test.tsx, src/components/Input/Input.test.tsx, src/components/PasswordToggle/PasswordToggle.test.tsx, src/components/Select/Select.test.tsx, src/components/Slider/Slider.test.tsx, src/components/Textarea/Textarea.test.tsx
- Removed bold "Error:"/"Caution:"/"Success:" prefix in input field validation message.
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
- Go to [Input](https://react-components-1063.demos.haus/?path=/docs/input--docs) page in storybook.
- Check examples for [Error](https://react-components-1063.demos.haus/?path=/story/input--error)/[Success](https://react-components-1063.demos.haus/?path=/story/input--success)/[Caution](https://react-components-1063.demos.haus/?path=/story/input--caution). There should be no bold prefix before the message itself.
=> fix(field): remove bold prefix for error/caution/success validation

src/components/SearchBox/SearchBox.tsx
- Make `SearchBox` trigger search on Enter keydown, and blur the input field.
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
- Check `SearchBox` examples in [Storybook](https://react-components-1065.demos.haus/?path=/docs/searchbox--docs#default)
- Press "Enter" on the enabled examples and see that the input field blurs
This should not produce visual changes in Percy.
=> fix(searchbox): handle Enter key in the input field to search + blur

src/components/Textarea/Textarea.test.tsx, src/components/Textarea/Textarea.tsx
- Allow setting the value to an empty string. Otherwise, the previous value isn't updated.
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
You should be able to replicate this in a simplified example such as the one in the issue (#1068).
No visual change
Fixes: #1068
=> fix(textarea): reset value to an empty string

src/components/Tooltip/Tooltip.tsx
- tooltip should not reopen when target element is not hovered anymore. Tooltip was running multiple timers in the background, that would reopen it after it was closed.
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
- hover a tooltip and quickly move the mouse over the target element. The tooltip should close and not reopen
Fixes: #1073
=> fix: tooltip should not reopen when target element is not hovered anymore

src/components/ConfirmationModal/ConfirmationModal.tsx
- Allow loading state for the confirm button in the modal
- Allow disabled state for the confirm button in the modal
=> feat: allow loading and disable state for confirm button in ConfirmationModal

.github/workflows/pr-labels.yml
- Switch to `pull_request_target` to allow workflow to add commets on PRs from forks
needs to be merged to qa
=> ci: Update Percy label workflow to make it work on forks

src/components/Button/Button.stories.mdx, src/components/Button/Button.test.tsx, src/components/Button/Button.tsx, src/components/ContextualMenu/ContextualMenu.test.tsx, src/components/TablePagination/__snapshots__/TablePagination.test.tsx.snap
- feat: allow focusing disabled buttons and displaying tooltips
- this allows to display associated tooltips via keyboard
Previously, `disabled` attribute was used which prevents focusing the button entirely. This meant that users navigating by keyboard could not focus the button and any associated tooltip would not be displayed.
By switching to aria-disabled, the button can still be focused while conveying its disabled state to assistive technologies. Submit action is prevented by using `.preventDefault`.
https://css-tricks.com/making-disabled-buttons-more-inclusive/
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
yarn add …
```
=> feat: allow focusing disabled buttons and displaying tooltips

src/components/EmptyState/EmptyState.stories.mdx, src/components/EmptyState/EmptyState.test.tsx, src/components/EmptyState/EmptyState.tsx
- Made `EmptyState` component design be consistent with [No content Empty State](https://vanillaframework.io/docs/patterns/empty-state#no-content) in Vanilla Framework.
- #1071
=> fix: make EmptyState implementation consistent with Vanilla Framework

.github/workflows/tics-coverage.yml
- Added GH action workflow to run test coverage and upload TICS report to TIOBE
- Verify that the [test run](https://github.com/canonical/react-components/actions/runs/9108936123/job/25040738406?pr=1087) of this action succeeded 
- You can ignore that the CI job is listed as failed in CI checks on PR
=> ci: Add GitHub action to upload TICS report to TIOBE

README.md
Added a section to the README which lists projects related to or that build upon this library.
- Look at README
- Does it make sense?
=> docs: Add section to README to list related projects

src/components/Textarea/Textarea.stories.mdx, src/components/Textarea/Textarea.test.tsx, src/components/Textarea/Textarea.tsx
…ithin a text area.
- Added functionality such that a function pass through by "onControlEnter" (for example a submission function) can be executed when CTRL+ENTER are clicked whilst within the textarea.
- Implemented a jest test to verify that the component "adds Ctrl + Enter keydown event listener on mount and removes on unmount".
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
- Navigate to the textarea component.
- Pres CTRL and Enter at the same time whilst within the component, and note an "alert" function occur.
- List any expected visual change in Percy, or write something like "No visual changes …
=> feat(textarea component): Enable control+enter form submission from within a text area [WD-10959]

src/components/Accordion/Accordion.stories.mdx, src/components/Accordion/AccordionSection/AccordionSection.test.tsx, src/components/Accordion/AccordionSection/AccordionSection.tsx
- Changed the type of the `title` prop of the `AccordionSection` to be `ReactNode` instead of `string`. Since `ReactNode` is a superset of `string`, it is automatically backward-compatible and non-breaking.
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
- Check the newly added accordion example in Storybook.
- One example was added to the accordion page of the Storybook, so that is likely to be flagged as a diff by Percy. Nothing else should be flagged.
=> feat(accordion): allow to use a ReactNode as title for an accordion

src/components/Panel/Panel.stories.tsx, src/components/Panel/Panel.test.tsx, src/components/Panel/Panel.tsx, src/components/Panel/index.ts, src/index.ts, src/types/index.ts, src/utils.ts
- Add the Panel component that is used within the application layout.
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
- Open the demo and go to the panel example (under components at the bottom).
- Check that the docs look OK.
=> feat: add application layout Panel component

.github/workflows/tics-coverage.yml
For security reasons we are removing the step that uploads TICS report as action artifact.
=> ci(tics): Don't upload TICS report to artifacts

src/components/ApplicationLayout/ApplicationLayout.stories.tsx, src/components/ApplicationLayout/ApplicationLayout.test.tsx, src/components/ApplicationLayout/ApplicationLayout.tsx
- Prevented display of an empty app navigation panel when passing no `navItems` and `undefined` as `sideNavigation` props.
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
- Check the new "No Navigation" story for ApplicationLayout in Storybook: it displays no app navigation at all.
- There should be a new story in Storybook for ApplicationLayout, called "No Navigation". This should be the only visual difference.
=> fix(app-layout): prevent display of empty app navigation panel

src/components/ConfirmationButton/ConfirmationButton.tsx, src/components/ConfirmationModal/ConfirmationModal.test.tsx, src/components/ConfirmationModal/ConfirmationModal.tsx
- Support non-string button labels in the confirmation modal.
=> feat: non-string button labels

src/components/ContextualMenu/ContextualMenu.tsx, src/components/ContextualMenu/ContextualMenuDropdown/ContextualMenuDropdown.test.tsx, src/components/ContextualMenu/ContextualMenuDropdown/ContextualMenuDropdown.tsx
… vertically
- Added a scss file for Contextual Menu
- Implemented initial logic by @mas-who to vertically position the Menu optimally based on the viewport height.
- Then transferred this logic from AdjustVerticalHeight function in Contextual Menu, to updateVerticalPosition function in ContextualMenuDropdown.tsx such that the menu may be adjusted according to both the container height and the viewport height.
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
N/A
- Contextual Menu dropdown now displays "upwards" if there is not enough space downwards.
=> chore: Allow Contextual Menu Component to be positioned optimally [WD-10977]

src/components/ContextualMenu/ContextualMenu.test.tsx, src/components/ContextualMenu/ContextualMenu.tsx, src/components/MultiSelect/MultiSelect.scss, src/components/MultiSelect/MultiSelect.test.tsx, src/components/MultiSelect/MultiSelect.tsx
- Replace internals of MultiSelect with ContextualMenu so it uses a portal to fix overflow: hidden issues.
- Go to the [MultiSelect demo](https://react-components-1117.demos.haus/?path=/docs/components-multiselect--docs).
- Open the dropdown and it shouldn't get cut off by the frame around the example.
Fixes: #1116.
=> refactor: replace internals of MultiSelect with ContextualMenu

src/components/SearchBox/SearchBox.test.tsx, src/components/SearchBox/SearchBox.tsx
- Update SearchBox to have a prop to disable blurring on search.
- Pass the search value to the onSearch prop.
- Go to [this demo](https://react-components-1115.demos.haus/?path=/story/components-searchbox--default&args=shouldBlurOnSearch:!false)
- In the controls tab set `shouldBlurOnSearch` to "false"
- Type something into the search box and press enter.
- The input should not blur.
=> feat: support not blurring when searching

src/components/SideNavigation/SideNavigationItem/SideNavigationItem.tsx, src/components/SideNavigation/SideNavigationLink/SideNavigationLink.tsx
- use forwardRef in SideNavigationLink Component
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
Fixes: # .
=> chore: forwardRef from SideNavigationLink component

package.json
With the migration to use React's `useId` we require the use of React 18, because that's where it was introduced.
This removes the peer dependency of React 17.
Related to: https://github.com/canonical/react-components/pull/1050
=> chore(dependencies): Require React 18

src/components/ActionButton/ActionButton.test.tsx, src/components/NotificationProvider/NotificationProvider.test.tsx
This PR fixes deprecation warning about act usage from `react-dom/test-utils`
- test: test: fix deprecated act usage warning
- update act import from react
- remove act in favour of async userEvent
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
Fixes: # .
=> test: fix deprecated act usage warning

src/components/SideNavigation/SideNavigationItem/SideNavigationItem.tsx, src/components/SideNavigation/SideNavigationLink/SideNavigationLink.test.tsx, src/components/SideNavigation/SideNavigationLink/SideNavigationLink.tsx
- Fixes #1122 
- [WD-14675](https://warthogs.atlassian.net/browse/WD-14675)
- No visual changes expected
[WD-14675]: https://warthogs.atlassian.net/browse/WD-14675?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: forwardRef from SideNavigationLink component

src/components/Chip/Chip.tsx, src/components/SearchAndFilter/SearchAndFilter.test.tsx, src/components/SearchAndFilter/SearchAndFilter.tsx
Fixes the search & filter component re-opening the filter panel when removing a filter. The component will now behave as it does in the [behaviour spec](https://discourse.ubuntu.com/t/behaviour-delete-a-filter-chip/21546)
The search & filter component has an [on-click handler](https://github.com/canonical/react-components/blob/288b3856b3133e14b8ced3b5b830211403eb92bd/src/components/SearchAndFilter/SearchAndFilter.tsx#L239) that opens the filter panel. This is currently being triggered by any clicks within the search and filter element and its descendants. This means that when a user clicks a chip dismissal button, the event bubbles up to the search & filter component & shows the filter panel.
1. Added the dismissal event to the parameter list of the `Chip` component's `onDismiss` …
=> fix: search and filter panel no longer opens when dismissing a filter

src/components/SideNavigation/SideNavigationBase/SideNavigationBase.tsx, src/components/SideNavigation/SideNavigationLink/SideNavigationLink.test.tsx, src/components/SideNavigation/SideNavigationLink/SideNavigationLink.tsx
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
Fixes: [WD-14589](https://warthogs.atlassian.net/browse/WD-14589)
[WD-14589]: https://warthogs.atlassian.net/browse/WD-14589?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(side nav): Pass ref to SideNavBase and write a test

src/utils.test.ts, src/utils.ts
- Fixed issue with `highlightSubstring` breaking related UI components for special character inputs such as `\`
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
- Navigate to the `SearchAndFilter` component in storybook and type `\`. It should no longer break the UI.
=> fix: fix highlightSubstring not being able to handle special characters for regex

src/components/SideNavigation/SideNavigationLink/SideNavigationLink.test.tsx, src/components/SideNavigation/SideNavigationLink/SideNavigationLink.tsx
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
Fixes: # .
=> fix: Update SideNavigationLink component's prop type

README.md
Attempting to trigger the release.
=> feat: Fixing readme (to trigger the release of ESM)

src/components/CodeSnippet/CodeSnippet.stories.tsx
Removes iframe from CodeSnippet example to fix unstable Percy tests.
Drive-by: fix spacing in the JSX code elements example
Fixes #1144 
- Check demo: https://react-components-1145.demos.haus/?path=/docs/components-codesnippet--docs#content
- Make sure example is not using iframe
- Check following example, make sure there are spaces in `snap install toto`
=> fix(CodeSnippet): Remove iframe from CodeSnippet example

src/components/Stepper/Step/Step.scss, src/components/Stepper/Step/Step.stories.tsx, src/components/Stepper/Step/Step.test.tsx, src/components/Stepper/Step/Step.tsx, src/components/Stepper/Step/index.tsx, src/components/Stepper/Stepper.stories.tsx, src/components/Stepper/Stepper.test.tsx, src/components/Stepper/Stepper.tsx, src/components/Stepper/__snapshots__/Stepper.test.tsx.snap, src/components/Stepper/index.ts, src/index.ts
- Added stepper wrapper component
- Added step component with options to:
- add a title for the step 
- enable/disable the step
- select the step
- display an optional label
- display an optional link
- display a progress line
- display the index of the step
- display an icon for the step
- Added tests for the step component
- Added tests for the stepper component 
The current stepper component is of the standard size outlined in the spec. If required, the large size can be added at a later time.
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
- List any expected visual change in Percy, or …
=> feat: add stepper and step components

src/components/DoughnutChart/DoughnutChart.scss, src/components/DoughnutChart/DoughnutChart.stories.tsx, src/components/DoughnutChart/DoughnutChart.test.tsx, src/components/DoughnutChart/DoughnutChart.tsx, src/components/DoughnutChart/index.ts, src/index.ts
- Added the Doughnut Chart Component
- ~~Correct failing test that verifies whether a tooltip shows on hover.~~
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
- Navigate to Doughnut Chart component
Fixes: N/A
=> feat: Upstream Doughnut Chart to RC

package.json, yarn.lock
- Update vanilla-framework dependency to version 4.18.0.
- Update sass dependency to version 1.79.4 (aligning with the version used by vanilla-framework). This update addresses compatibility issues with the new Sass syntax. See details https://github.com/canonical/vanilla-framework/pull/5370.
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
Fixes: # .
=> chore(dependencies): Vanilla update to latest version (with sass)

.storybook/addons/withTheme.css, .storybook/addons/withTheme.jsx, .storybook/preview.js
- Hide default background select
- Add global theme select Light/Dark/Paper for strorybook
- Add HOC decorator for all stories
- Add special hack for docs background
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
Fixes: # .
=> docs(storybook): Theming support for stories

src/components/TablePagination/TablePaginationControls/TablePaginationControls.test.tsx, src/components/TablePagination/TablePaginationControls/TablePaginationControls.tsx
- Hide the total pages text when **showPageInput** is set to `false`
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
- Set `showPageInput` to `false` in the **ControlsOnly** example of `TablePagination.stories.tsx`.
- You should not see any text between the buttons in the **Controls Only** example of `TablePagination`.
Fixes: https://chat.canonical.com/canonical/pl/6paertj3fpd3jkutj7j69715jw
=> fix(TablePaginationControls): Hide total pages text when page input is hidden

src/components/SearchAndFilter/SearchAndFilter.tsx
- avoid trapping tab key presses when the search and filter is closed
```shell
yarn start
```
- open the search and filter in storybook
- press tab and ensure you can tab over the closed search and filter with few tab key presses
- previously, all the hidden chips in the hidden search and filter panel would trap the tab key.
=> fix: avoid trapping tab key presses when the search and filter is closed

src/components/CustomSelect/CustomSelect.scss, src/components/CustomSelect/CustomSelect.stories.tsx, src/components/CustomSelect/CustomSelect.test.tsx, src/components/CustomSelect/CustomSelect.tsx, src/components/CustomSelect/CustomSelectDropdown/CustomSelectDropdown.test.tsx, src/components/CustomSelect/CustomSelectDropdown/CustomSelectDropdown.tsx, src/components/CustomSelect/CustomSelectDropdown/__snapshots__/CustomSelectDropdown.test.tsx.snap, src/components/CustomSelect/CustomSelectDropdown/index.ts, src/components/CustomSelect/__snapshots__/CustomSelect.test.tsx.snap, src/components/CustomSelect/index.ts, src/index.ts
- Upstream `CustomSelect` component from lxd-ui
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
- Check selecting an option
- Check search functionality
- Check height adjustment against viewport size
- Check keyboard navigation
=> feat(CustomSelect): Upstream CustomSelect component [WD-17720]

src/components/Button/Button.stories.tsx
- Updated Storybook example for the "[Link button](https://react-components-1176.demos.haus/?path=/story/components-button--link)"
- Added the "Button as link" story at the bottom
- Added descriptions for all the button stories
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
- Check the updated Storybook example for the "[Link button](https://react-components-1176.demos.haus/?path=/story/components-button--link)" - it should now look like a link, instead of a base button.
- Check that the storybook page for the `Button` component looks as expected
- Confirm that the only visual changes are in the "Button" …
=> fix(button): link button example in storybook was using base appearance

src/components/Modal/Modal.stories.tsx, src/components/Modal/Modal.test.tsx, src/components/Modal/Modal.tsx
- add option to the `Modal` component to prevent close on outside click behaviour.
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
- Go to the `Modal` component in storybook and set the `closeOnOutsideClick` control to `false`, make sure clicking outside of the modal does not close it.
=> feat: prevent modal from closing when clicking outside

eslint.config.mjs
- Ignore the lint errors coming from external modules. Fixing these will change the behaviour of those modules.
Go to the `Files changed` tab on this PR and there should be no lint warnings from `usePortal`.
=> chore(lint): ignore lint errors from externals

babel.config.js, package.json, src/components/NotificationProvider/NotificationProvider.tsx, yarn.lock
- Replace deprecated deps with their updated equivalents (I chose fast-deep-equal because it's already a sub-dependency).
=> chore(deps): replace deprecated deps

src/components/Notification/Notification.test.tsx, src/components/Notification/Notification.tsx, src/components/NotificationProvider/__snapshots__/NotificationProvider.test.tsx.snap
- Add `type="button"` prop to notification action buttons and dismiss button
- Allow passing in `ReactNode` to notification actions
- No visual changes expected.
=> refactor(Notification): Add type="button" and allow passing in ReactNode to Notification Actions

src/components/ConfirmationButton/ConfirmationButton.stories.tsx, src/components/ConfirmationButton/ConfirmationButton.test.tsx, src/components/ConfirmationButton/ConfirmationButton.tsx
- Add a pre modal open hook
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
- Go to https://react-components-1190.demos.haus/?path=/story/components-confirmationbutton--with-should-show-modal-handler
- Make sure the buttons work
- No visual changes expected.
=> feat(ConfirmationButton): Add pre modal open hook

.github/workflows/tics-coverage.yml
TICS uploads are [currently failing with a 401 unauthorized error](https://github.com/canonical/react-components/actions/runs/14358736656/job/40254602990). This is because the TICS token [was recently migrated](https://chat.canonical.com/canonical/pl/czanfrzz8fn4ugugy5h3sfjfqh), and we are still using the old `TICS_AUTH_TOKEN`. 
This updates the TICS workflow to use the new secret, per [example](https://chat.canonical.com/canonical/pl/yjdtscej13bm9btcy4sxn56ger) from @jw-can 
Go to the [secrets page](https://github.com/canonical/react-components/settings/secrets/actions) and verify that the secret name used in this PR matches the new org TICS secret name.
```shell
yarn start
```
```shell
yarn build
npm …
```
=> chore(TICS): Migrate to new org TICS token

src/components/CustomSelect/CustomSelectDropdown/__snapshots__/CustomSelectDropdown.test.tsx.snap, src/components/SearchBox/SearchBox.tsx
- Fixes an accessibility issue in the `SearchBox` component by dynamically setting the label’s `htmlFor` to match the input id, when provided. 
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
=> fix: dynamically set label to match id

src/components/Slider/Slider.tsx
- Resolves "Missing form label" a11y issue flagged by WAVE
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
=> fix(a11y): add label to number input in slider

src/components/Stepper/Step/Step.scss, src/components/Switch/Switch.scss, src/components/Switch/Switch.stories.tsx, src/components/Switch/Switch.test.tsx, src/components/Switch/Switch.tsx
- Add optional help text to switch component
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
Fixes: #[WD-13578](https://warthogs.atlassian.net/browse/WD-13578)
[WD-13578]: https://warthogs.atlassian.net/browse/WD-13578?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add help text to switch component

src/components/Notifications/ToastNotification/Toast.scss
- Using the dvh unit instead of vh ensures that the address bar on mobile browsers is not counted as part of the viewport height.
=> fix(toast): improve mobile compatibility by using dvh unit instead of vh

src/components/Notifications/ToastNotification/ToastNotificationList.tsx
- Fix an edge case where filters weren't reset when the filtered notifications were individually dismissed 
Before:
https://github.com/user-attachments/assets/344612bd-7b24-4727-a704-43f1404e544f
After:
https://github.com/user-attachments/assets/8d0994ad-a54a-4844-b867-fd97bad85b6a
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
- select a filter
- dismiss all the notifications in that filter by clicking the close (X) icon within each notification
- confirm that the filters are reset when all the filtered notifications are closed
- No visual changes expected
=> fix: reset filters when all filtered notifications are closed

package.json, src/components/TablePagination/TablePagination.scss, yarn.lock
- fix(table-pagination) encounter more space for pagination, as the horizontal input padding in vanilla increased
- this is to fix fallout from https://github.com/canonical/vanilla-framework/pull/5539
- for the problematic pagination see [this demo](https://react-components-1198.demos.haus/?path=/story/components-tablepagination--default) from https://github.com/canonical/react-components/pull/1198
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
- check the [table pagination](https://react-components-1210.demos.haus/?path=/story/components-tablepagination--default) with new vanilla version
- Table …
=> fix: table-pagination to encounter more space to fit content

src/components/TablePagination/TablePagination.scss, src/components/TablePagination/TablePaginationControls/TablePaginationControls.tsx, src/components/TablePagination/__snapshots__/TablePagination.test.tsx.snap
- fix: table-pagination on small screens. adjust spacing and avoid line breaks
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
- Open the [table pagination](https://react-components-1211.demos.haus/?path=/story/components-tablepagination--default) in storybook
- Select a small mobile screen and ensure it looks good
Discovered in https://github.com/canonical/lxd-ui/pull/1306
before
after
=> fix: table-pagination on small screens. adjust spacing and avoid line breaks

src/components/TablePagination/TablePaginationControls/TablePaginationControls.test.tsx, src/components/TablePagination/TablePaginationControls/TablePaginationControls.tsx, src/components/TablePagination/TablePaginationControls/__snapshots__/TablePaginationControls.test.tsx.snap, src/components/TablePagination/__snapshots__/TablePagination.test.tsx.snap
In Safari, when the `TablePagination` component displays only one page of data, the number input field's native stepper controls (up/down arrows) remain enabled and functional, creating a confusing user experience. Additionally, users can clear the input field and leave it empty, which should not be possible when there's only one valid page.
**Sidenote**: Although, main issue #1212 only mentioned Safari, this doesn't seem to only a Safari issue. I was able to reproduce it on Arc Browser.
This PR fixes the issue by properly disabling the page number input field in the `TablePaginationControls` component when there's only one page or no pages. The solution uses the `disabled` attribute to completely prevent user interaction with the input field, ensuring that:
- Native browser stepper …
=> fix: disable input controls when there is only one page in TablePagination

.circleci/config.yml
- Replaces the installation of `libasound2` with `libasound2t64` in the CirlceCI config for Percy, as `libasound2` is no longer in the package sources. In Noble, [libasound2 was renamed to libasound2t64](https://github.com/cypress-io/cypress-documentation/issues/5816). 
- Removes dependencies `gconf-service`, `libgconf-2-4`, `libappindicator1` as they are not currently listed on the [Puppeteer Linux deps page](https://pptr.dev/troubleshooting#chrome-doesnt-launch-on-linux)
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
- See if Percy passes
- No visual changes expected
Fixes: …
=> chore(Percy): fix Puppeteer dependency installation failing

src/components/ConfirmationModal/ConfirmationModal.tsx, src/components/Modal/Modal.tsx
- Add `type="button"` to Close button in **Modal** to avoid submission in a form context
- Add `type="button"` to Cancel button in **ConfirmationModal**
```shell
yarn start
```
- No visual changes expected
=> fix: set type button on modal close buttons

src/components/Stepper/Step/Step.scss
- fix(step) use vanilla theme colors for stepper component
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
- check the stepper component in storybook
- the selected colors on the stepper component should be a bit more visible, the background of the active step is more visible. the outline of an active step circle should be improved.
=> fix(step): use vanilla theme colors for stepper component

src/components/Notifications/ToastNotification/Toast.scss
- fix(toast) ensure toast notifications are shown above side panels
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
- not needed
- none expected
=> fix(toast): ensure toast notifications are shown above side panels

src/components/Stepper/Step/Step.scss, src/components/Stepper/Stepper.stories.tsx
Previously, `width: fit-content` caused uneven widths in the vertical stepper, which was visible when individual steps were selected. Updated it to `inherit` for vertical steppers.
**Before**
**After**
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
=> fix(step): inherit stepper's width for steps

src/components/SidePanel/SidePanel.stories.tsx, src/components/SidePanel/SidePanel.test.tsx, src/components/SidePanel/SidePanel.tsx, src/components/SidePanel/__snapshots__/SidePanel.test.tsx.snap
- fix(sidepanel) default size of sidepanel to be standard, allow for narrow and wide sizes
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
- check [sidepanel component](https://react-components-1229.demos.haus/?path=/docs/components-sidepanel--docs) default to be standard size, with options for narrow and wide
- sidepanel width should be a bit more as the narrow is not the default anymore.
=> fix(sidepanel): default size of sidepanel to be standard, allow for narrow and wide sizes

src/components/ThemeSwitcher/ThemeSwitcher.stories.tsx, src/components/ThemeSwitcher/ThemeSwitcher.test.tsx, src/components/ThemeSwitcher/ThemeSwitcher.tsx, src/components/ThemeSwitcher/__snapshots__/ThemeSwitcher.test.tsx.snap, src/components/ThemeSwitcher/index.ts, src/index.ts
- add new component ThemeSwitcher to apply dark and light theme and switch between them easily
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
- open the [ThemeSwitcher in storybook](https://react-components-1230.demos.haus/?path=/docs/components-themeswitcher--docs) and ensure it works as expected
- New screens for the ThemeSwitcher default story should be accepted.
=> feat(theme-switcher): add new component to apply dark and light theme and switch between them easily

src/components/Chip/Chip.stories.tsx, src/components/Chip/Chip.test.tsx, src/components/Chip/Chip.tsx, src/components/StatusLabel/StatusLabel.tsx
- React implementation of https://github.com/canonical/vanilla-framework/pull/5555 . Will not appear as expected until that is merged and released (expected Vanilla 4.25.0).
- Implements the new read-only, badged, and icon Chips.
- Implements some Chip states that have been in Vanilla for a while but have not been added to React Components - dense & inline
- Deprecates the Status Label component.
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
1. Open [read-only chip](https://react-components-1217.demos.haus/?path=/story/components-chip--read-only). …
=> feat: support new chip variants (read-only, icon, badged), deprecate StatusLabel

src/components/NotificationProvider/index.ts, src/components/NotificationProvider/messageBuilder.tsx, src/components/Notifications/ToastNotification/ToastNotification.stories.tsx, src/components/Notifications/ToastNotification/ToastNotificationProvider.tsx
- Added id prop to `success`, `failure`, `info`, and `caution` methods from `ToastNotificationProvider`
- (driveby) Use `messageBuilder` functions when adding toast notifications
- (driveby) extract error message formatting from `failure` message builder
- (driveby) add button to storybook to add a warning notification
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
- Go to toast notifications
- Click "Add warning"
- Ensure a caution/warning notification is added to the list
- Ensure the counter for warnings is incremented by 1
=> feat(ToastNotifications): Allow id to be overwritten by notify functions

src/components/ScrollableTable/ScrollableTable.scss, src/components/ScrollableTable/ScrollableTable.stories.tsx, src/utils.ts
- Fixes linked issue (#1245).
- Fixes a bug that causes padding to be added twice in `getElementAbsoluteHeight` helper function.
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
- Go to "ScrollableTable" -> "Responsive" example in Storybook.
- Resize the window width and check that the issue described in #1245 is solved.
The only visual change expected is the capture of two snapshots of the "Responsive" story for the `ScrollableTable`, at 768px and 1280px width.
Fixes: #1245
=> fix: The responsive behaviour of the `MainTable` wrapped inside a `ScrollableTable` is not equivalent to the default case

src/components/MultiSelect/MultiSelect.scss, src/components/MultiSelect/MultiSelect.stories.tsx, src/components/MultiSelect/MultiSelect.tsx
- fix(MultiSelect): disabled for non search variant
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
- Existing stories should be unchanged
- New story with disabled: true should render a disabled button
- When MultiSelect is disabled and variant is not search, button is disabled 
- No visual changes expected for search variant
=> fix(MultiSelect): disabled for non search variant

src/components/MultiSelect/MultiSelect.stories.tsx, src/components/MultiSelect/MultiSelect.test.tsx, src/components/MultiSelect/MultiSelect.tsx
- feat(MultiSelect): implement help as a helper text underneath the component
```shell
yarn start
```
```shell
yarn build
npm pack
```
```shell
```
- Check that MultiSelect with help displays a helper text
- Check that MultiSelect without help remains unchanged
=> feat(MultiSelect): implement help
